/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residentsupportsystem;

import java.util.List;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lukerenwick
 */
public class AdminManageInquirys extends javax.swing.JFrame {

    int userLoggedIn;
    Inquiry inquiry = new Inquiry();
    Client client = new Client();
    Appointment appointment = new Appointment();
    
    public AdminManageInquirys(int userID) {
        userLoggedIn = userID;
        initComponents();
        inquiry.setEnquiryTable(enquiryTablejTable);
        client.setClientTable(clientTablejTable);
        appointment.setAvailableAppointmentTable(appointmentTablejTable);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowjPanel = new javax.swing.JPanel();
        enquiryDetailsjPanel = new javax.swing.JPanel();
        enquiryTypejPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxHousing = new javax.swing.JCheckBox();
        jCheckBoxDebt = new javax.swing.JCheckBox();
        jCheckBoxBenefits = new javax.swing.JCheckBox();
        jCheckBoxEmployment = new javax.swing.JCheckBox();
        jCheckBoxDomestic = new javax.swing.JCheckBox();
        jCheckBoxOther = new javax.swing.JCheckBox();
        searchjPanel = new javax.swing.JPanel();
        jLabelClientName = new javax.swing.JLabel();
        jLabelClientID = new javax.swing.JLabel();
        jTextFieldClientID = new javax.swing.JTextField();
        jTextFieldClientName = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonSearchAll = new javax.swing.JButton();
        notesjPanel = new javax.swing.JPanel();
        jLabelNotes = new javax.swing.JLabel();
        jTextEnquiryNotes = new javax.swing.JTextField();
        backjButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        newjButton = new javax.swing.JButton();
        savejButton = new javax.swing.JButton();
        dateAndTimejPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDate_Time = new javax.swing.JTextField();
        enquiryIDjPanel = new javax.swing.JPanel();
        dateAndTimejPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        enquiryIDjTextField = new javax.swing.JTextField();
        dateAndTimejPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxEnquiryStatus = new javax.swing.JComboBox<>();
        enquiryTablejScrollPane = new javax.swing.JScrollPane();
        enquiryTablejTable = new javax.swing.JTable();
        clientTablejScrollPane = new javax.swing.JScrollPane();
        clientTablejTable = new javax.swing.JTable();
        headerjPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        appointmentTablejScrollPane = new javax.swing.JScrollPane();
        appointmentTablejTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        appointmentIDjLabel = new javax.swing.JLabel();
        appointmentDatejLabel = new javax.swing.JLabel();
        appointmentFromjLabel = new javax.swing.JLabel();
        appointmentTojLabel = new javax.swing.JLabel();
        appointmentCaseworkerjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentNotesjTextArea = new javax.swing.JTextArea();
        assignAppointmentjButton = new javax.swing.JButton();
        appointmentNotesjLabel = new javax.swing.JLabel();
        appointmentIDjTextField = new javax.swing.JTextField();
        appointmentDatejTextField = new javax.swing.JTextField();
        appointmentStartjTextField = new javax.swing.JTextField();
        appointmentEndjTextField = new javax.swing.JTextField();
        appointmentCaseworkerjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowjPanel.setBackground(new java.awt.Color(47, 54, 64));

        enquiryDetailsjPanel.setBackground(new java.awt.Color(47, 54, 64));

        enquiryTypejPanel.setBackground(new java.awt.Color(113, 128, 147));

        jLabel1.setText("Nature of Enquiry");

        jCheckBoxHousing.setText("Housing");
        jCheckBoxHousing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHousingActionPerformed(evt);
            }
        });

        jCheckBoxDebt.setText("Debt");

        jCheckBoxBenefits.setText("Benefits");

        jCheckBoxEmployment.setText("Employment");
        jCheckBoxEmployment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEmploymentActionPerformed(evt);
            }
        });

        jCheckBoxDomestic.setText("Domestic");

        jCheckBoxOther.setText("Other");

        javax.swing.GroupLayout enquiryTypejPanelLayout = new javax.swing.GroupLayout(enquiryTypejPanel);
        enquiryTypejPanel.setLayout(enquiryTypejPanelLayout);
        enquiryTypejPanelLayout.setHorizontalGroup(
            enquiryTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enquiryTypejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enquiryTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enquiryTypejPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(enquiryTypejPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(enquiryTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxDomestic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxHousing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(enquiryTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxEmployment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(enquiryTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxOther, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );
        enquiryTypejPanelLayout.setVerticalGroup(
            enquiryTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enquiryTypejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enquiryTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(enquiryTypejPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBoxDebt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxOther))
                    .addGroup(enquiryTypejPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(enquiryTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHousing)
                            .addComponent(jCheckBoxBenefits))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(enquiryTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxEmployment)
                            .addComponent(jCheckBoxDomestic))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchjPanel.setBackground(new java.awt.Color(113, 128, 147));

        jLabelClientName.setText("Client Name:");

        jLabelClientID.setText("Client ID:");

        jTextFieldClientID.setBackground(new java.awt.Color(220, 221, 225));

        jTextFieldClientName.setBackground(new java.awt.Color(220, 221, 225));

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonSearchAll.setText("Search all");
        jButtonSearchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchjPanelLayout = new javax.swing.GroupLayout(searchjPanel);
        searchjPanel.setLayout(searchjPanelLayout);
        searchjPanelLayout.setHorizontalGroup(
            searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchjPanelLayout.createSequentialGroup()
                        .addGroup(searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelClientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelClientID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldClientName, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jTextFieldClientID)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchjPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSearchAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch)))
                .addContainerGap())
        );
        searchjPanelLayout.setVerticalGroup(
            searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientID)
                    .addComponent(jTextFieldClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientName)
                    .addComponent(jTextFieldClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonSearchAll))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        notesjPanel.setBackground(new java.awt.Color(113, 128, 147));

        jLabelNotes.setText("Notes:");

        jTextEnquiryNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEnquiryNotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout notesjPanelLayout = new javax.swing.GroupLayout(notesjPanel);
        notesjPanel.setLayout(notesjPanelLayout);
        notesjPanelLayout.setHorizontalGroup(
            notesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notesjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTextEnquiryNotes)
        );
        notesjPanelLayout.setVerticalGroup(
            notesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notesjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEnquiryNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        deletejButton.setText("Add to Waiting List");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });

        newjButton.setText("New");
        newjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newjButtonActionPerformed(evt);
            }
        });

        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        dateAndTimejPanel.setBackground(new java.awt.Color(113, 128, 147));

        jLabel2.setText("Enquiry Date & Time:");

        jTextFieldDate_Time.setBackground(new java.awt.Color(220, 221, 225));
        jTextFieldDate_Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDate_TimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dateAndTimejPanelLayout = new javax.swing.GroupLayout(dateAndTimejPanel);
        dateAndTimejPanel.setLayout(dateAndTimejPanelLayout);
        dateAndTimejPanelLayout.setHorizontalGroup(
            dateAndTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateAndTimejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDate_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dateAndTimejPanelLayout.setVerticalGroup(
            dateAndTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateAndTimejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dateAndTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDate_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout enquiryIDjPanelLayout = new javax.swing.GroupLayout(enquiryIDjPanel);
        enquiryIDjPanel.setLayout(enquiryIDjPanelLayout);
        enquiryIDjPanelLayout.setHorizontalGroup(
            enquiryIDjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        enquiryIDjPanelLayout.setVerticalGroup(
            enquiryIDjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dateAndTimejPanel2.setBackground(new java.awt.Color(113, 128, 147));

        jLabel5.setText("Enquiry ID:");

        enquiryIDjTextField.setBackground(new java.awt.Color(220, 221, 225));
        enquiryIDjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enquiryIDjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dateAndTimejPanel2Layout = new javax.swing.GroupLayout(dateAndTimejPanel2);
        dateAndTimejPanel2.setLayout(dateAndTimejPanel2Layout);
        dateAndTimejPanel2Layout.setHorizontalGroup(
            dateAndTimejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateAndTimejPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enquiryIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        dateAndTimejPanel2Layout.setVerticalGroup(
            dateAndTimejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateAndTimejPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dateAndTimejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enquiryIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dateAndTimejPanel3.setBackground(new java.awt.Color(113, 128, 147));

        jLabel6.setText("Enquiry Status:");

        jComboBoxEnquiryStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select:", "OPEN", "CLOSED", "REFERRED", " " }));
        jComboBoxEnquiryStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEnquiryStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dateAndTimejPanel3Layout = new javax.swing.GroupLayout(dateAndTimejPanel3);
        dateAndTimejPanel3.setLayout(dateAndTimejPanel3Layout);
        dateAndTimejPanel3Layout.setHorizontalGroup(
            dateAndTimejPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateAndTimejPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxEnquiryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dateAndTimejPanel3Layout.setVerticalGroup(
            dateAndTimejPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateAndTimejPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dateAndTimejPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEnquiryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout enquiryDetailsjPanelLayout = new javax.swing.GroupLayout(enquiryDetailsjPanel);
        enquiryDetailsjPanel.setLayout(enquiryDetailsjPanelLayout);
        enquiryDetailsjPanelLayout.setHorizontalGroup(
            enquiryDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enquiryDetailsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enquiryDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(enquiryDetailsjPanelLayout.createSequentialGroup()
                        .addGroup(enquiryDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enquiryDetailsjPanelLayout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(enquiryIDjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(enquiryDetailsjPanelLayout.createSequentialGroup()
                                .addComponent(backjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletejButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(savejButton)
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(enquiryTypejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateAndTimejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateAndTimejPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateAndTimejPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notesjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        enquiryDetailsjPanelLayout.setVerticalGroup(
            enquiryDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enquiryDetailsjPanelLayout.createSequentialGroup()
                .addComponent(searchjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enquiryTypejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateAndTimejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateAndTimejPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateAndTimejPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notesjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(enquiryDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savejButton)
                    .addComponent(deletejButton)
                    .addComponent(newjButton)
                    .addComponent(backjButton))
                .addGap(138, 138, 138)
                .addComponent(enquiryIDjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        enquiryTablejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enquiry ID", "Admin", "Area", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enquiryTablejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enquiryTablejTableMouseClicked(evt);
            }
        });
        enquiryTablejScrollPane.setViewportView(enquiryTablejTable);

        clientTablejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client ID", "Firstname", "Lastname"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientTablejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTablejTableMouseClicked(evt);
            }
        });
        clientTablejScrollPane.setViewportView(clientTablejTable);

        headerjPanel.setBackground(new java.awt.Color(47, 54, 64));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 221, 225));
        jLabel3.setText("Manage Inquirys");

        javax.swing.GroupLayout headerjPanelLayout = new javax.swing.GroupLayout(headerjPanel);
        headerjPanel.setLayout(headerjPanelLayout);
        headerjPanelLayout.setHorizontalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerjPanelLayout.setVerticalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        appointmentTablejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appointment ID", "Date", "Start", "End", "Status", "Room"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentTablejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentTablejTableMouseClicked(evt);
            }
        });
        appointmentTablejScrollPane.setViewportView(appointmentTablejTable);

        jPanel1.setBackground(new java.awt.Color(113, 128, 147));

        appointmentIDjLabel.setText("Appointment ID");

        appointmentDatejLabel.setText("Appointment Date");

        appointmentFromjLabel.setText("From");

        appointmentTojLabel.setText("To");

        appointmentCaseworkerjLabel.setText("Caseworker");

        appointmentNotesjTextArea.setColumns(20);
        appointmentNotesjTextArea.setRows(5);
        jScrollPane1.setViewportView(appointmentNotesjTextArea);

        assignAppointmentjButton.setText("Assign Appointment");

        appointmentNotesjLabel.setBackground(new java.awt.Color(113, 128, 147));
        appointmentNotesjLabel.setText("Notes");

        appointmentIDjTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentDatejTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentStartjTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentEndjTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentCaseworkerjTextField.setBackground(new java.awt.Color(220, 221, 225));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(appointmentFromjLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(appointmentStartjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(appointmentTojLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(appointmentEndjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(appointmentCaseworkerjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(appointmentIDjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(appointmentDatejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(appointmentIDjTextField)
                                            .addComponent(appointmentDatejTextField)
                                            .addComponent(appointmentCaseworkerjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(assignAppointmentjButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(appointmentNotesjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentIDjLabel)
                    .addComponent(appointmentIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentDatejLabel)
                    .addComponent(appointmentDatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentFromjLabel)
                    .addComponent(appointmentTojLabel)
                    .addComponent(appointmentStartjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentEndjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentCaseworkerjLabel)
                    .addComponent(appointmentCaseworkerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(appointmentNotesjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignAppointmentjButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout windowjPanelLayout = new javax.swing.GroupLayout(windowjPanel);
        windowjPanel.setLayout(windowjPanelLayout);
        windowjPanelLayout.setHorizontalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowjPanelLayout.createSequentialGroup()
                .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(windowjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enquiryDetailsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientTablejScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(appointmentTablejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enquiryTablejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        windowjPanelLayout.setVerticalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowjPanelLayout.createSequentialGroup()
                .addComponent(headerjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enquiryTablejScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(windowjPanelLayout.createSequentialGroup()
                        .addComponent(clientTablejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appointmentTablejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enquiryDetailsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 645, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxHousingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHousingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHousingActionPerformed

    private void jCheckBoxEmploymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEmploymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEmploymentActionPerformed

    private void jTextEnquiryNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEnquiryNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEnquiryNotesActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed

        new AdminDashboard(userLoggedIn).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backjButtonActionPerformed

    private void jTextFieldDate_TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDate_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDate_TimeActionPerformed

    private void enquiryIDjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enquiryIDjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enquiryIDjTextFieldActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        String enquiryID = (enquiryIDjTextField.getText());
        String enquiryAdminID = (Integer.toString(userLoggedIn));
        String enquiryClientID = (jTextFieldClientID.getText());
        String enquiryArea = "";
        if (jCheckBoxDomestic.isSelected()){
            enquiryArea = "DOMESTIC ";
        }
        if (jCheckBoxHousing.isSelected()){
            enquiryArea = "HOUSING ";
        }
        if (jCheckBoxBenefits.isSelected()){
            enquiryArea = "BENEFITS ";
        }
        if (jCheckBoxEmployment.isSelected()){
            enquiryArea = "EMPLOYMENT ";
        }
        if (jCheckBoxDebt.isSelected()){
            enquiryArea =  "DEBT ";
        }
        if (jCheckBoxOther.isSelected()){
            enquiryArea =  "OTHER ";
        }
        
        String enquiryStatus = (jComboBoxEnquiryStatus.getSelectedItem().toString());
        String enquiryNotes = (jTextEnquiryNotes.getText());
        String enquiryDate =  (jTextFieldDate_Time.getText());
        
        if (inquiry.insertEnquiry(enquiryID, enquiryAdminID, enquiryClientID, enquiryArea, enquiryStatus, enquiryNotes, enquiryDate)){
            System.out.println("DATABASE UPDATED SUCCESSFULLY");
        }
        else {
            System.out.println ("DATABASE INSERT FAILED");
        }
    }//GEN-LAST:event_savejButtonActionPerformed

    private void jButtonSearchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchAllActionPerformed
       client.setClientTable(clientTablejTable);
    }//GEN-LAST:event_jButtonSearchAllActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
       String clientIDEntered = jTextFieldClientID.getText();
       client.setSearchedClientTable(clientTablejTable, clientIDEntered);
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void clientTablejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTablejTableMouseClicked
        int selectedClientID = clientTablejTable.getSelectedRow();
        String selectedClientPointer = (clientTablejTable.getValueAt(selectedClientID,0).toString());
        int selectedClient = Integer.parseInt(selectedClientPointer);
        inquiry.setUserSelectedClientEnquiryTable(enquiryTablejTable, selectedClient);
        
    }//GEN-LAST:event_clientTablejTableMouseClicked

    private void enquiryTablejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enquiryTablejTableMouseClicked
        int selectedEnquiryID = enquiryTablejTable.getSelectedRow();
        String selectedEnquiryPointer = (enquiryTablejTable.getValueAt(selectedEnquiryID,0).toString());
        int selectedEnquiry = Integer.parseInt(selectedEnquiryPointer);
        List dataList = inquiry.setEnquiryDetails(selectedEnquiry);
        System.out.println(dataList);
        enquiryIDjTextField.setText(dataList.get(0).toString());
        jTextFieldClientID.setText(dataList.get(1).toString());
        
        if (dataList.get(2).toString().equals("DOMESTIC")){
            resetCheckboxes();
            jCheckBoxDomestic.setSelected(true);
        }
        
        if (dataList.get(2).toString().equals("HOUSING")){
            resetCheckboxes();
            jCheckBoxHousing.setSelected(true);
        }
            
        if (dataList.get(2).toString().equals("BENEFITS")){
            resetCheckboxes();
            jCheckBoxBenefits.setSelected(true);
        }
        
        if (dataList.get(2).toString().equals("EMPLOYMENT")){
            resetCheckboxes();
            jCheckBoxEmployment.setSelected(true);
        }
        
        if (dataList.get(2).toString().equals("DEBT")){
            resetCheckboxes();
            jCheckBoxDebt.setSelected(true);
        }
         
        if (dataList.get(2).toString().equals("OTHER")){
            resetCheckboxes();
            jCheckBoxOther.setSelected(true);
        }
               
        jTextFieldClientName.setText(dataList.get(3).toString()+" "+ dataList.get(4).toString());
        jTextEnquiryNotes.setText(dataList.get(5).toString());
        jTextFieldDate_Time.setText(dataList.get(6).toString());
    }//GEN-LAST:event_enquiryTablejTableMouseClicked

    private void newjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newjButtonActionPerformed
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");  
        LocalDateTime dateToday = LocalDateTime.now();
        String newEnquiryDate = (dateFormat.format(dateToday));
        resetCheckboxes();
        enquiryIDjTextField.setText("");
        jTextFieldClientID.setText("");
        jTextFieldClientName.setText("");
        jTextEnquiryNotes.setText("");
        jTextFieldDate_Time.setText(newEnquiryDate);
    }//GEN-LAST:event_newjButtonActionPerformed

    private void jComboBoxEnquiryStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEnquiryStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEnquiryStatusActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void appointmentTablejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentTablejTableMouseClicked
        DefaultTableModel userTable = (DefaultTableModel)appointmentTablejTable.getModel();
        int selectedRow = appointmentTablejTable.getSelectedRow();
        String selectedAppointmentPointer = (userTable.getValueAt(selectedRow, 0).toString());
        int selectedAppointmentID = Integer.parseInt(selectedAppointmentPointer);			
        List resultSetArrayList = appointment.setAppointmentDetails(selectedAppointmentID);
        System.out.println(resultSetArrayList);
        appointmentIDjTextField.setText(resultSetArrayList.get(0).toString());
        appointmentDatejTextField.setText(resultSetArrayList.get(1).toString());
        appointmentStartjTextField.setText(resultSetArrayList.get(2).toString());
        appointmentEndjTextField.setText(resultSetArrayList.get(3).toString());
        appointmentNotesjTextArea.setText(resultSetArrayList.get(4).toString());
        appointmentCaseworkerjTextField.setText(resultSetArrayList.get(5).toString()+" "+resultSetArrayList.get(6).toString());
        
        
        
        
    }//GEN-LAST:event_appointmentTablejTableMouseClicked

    public void resetCheckboxes (){
         
         jCheckBoxDomestic.setSelected(false);
         jCheckBoxHousing.setSelected(false);
         jCheckBoxBenefits.setSelected(false);
         jCheckBoxEmployment.setSelected(false);
         jCheckBoxDebt.setSelected(false);
         jCheckBoxOther.setSelected(false);
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointmentCaseworkerjLabel;
    private javax.swing.JTextField appointmentCaseworkerjTextField;
    private javax.swing.JLabel appointmentDatejLabel;
    private javax.swing.JTextField appointmentDatejTextField;
    private javax.swing.JTextField appointmentEndjTextField;
    private javax.swing.JLabel appointmentFromjLabel;
    private javax.swing.JLabel appointmentIDjLabel;
    private javax.swing.JTextField appointmentIDjTextField;
    private javax.swing.JLabel appointmentNotesjLabel;
    private javax.swing.JTextArea appointmentNotesjTextArea;
    private javax.swing.JTextField appointmentStartjTextField;
    private javax.swing.JScrollPane appointmentTablejScrollPane;
    private javax.swing.JTable appointmentTablejTable;
    private javax.swing.JLabel appointmentTojLabel;
    private javax.swing.JButton assignAppointmentjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JScrollPane clientTablejScrollPane;
    private javax.swing.JTable clientTablejTable;
    private javax.swing.JPanel dateAndTimejPanel;
    private javax.swing.JPanel dateAndTimejPanel2;
    private javax.swing.JPanel dateAndTimejPanel3;
    private javax.swing.JButton deletejButton;
    private javax.swing.JPanel enquiryDetailsjPanel;
    private javax.swing.JPanel enquiryIDjPanel;
    private javax.swing.JTextField enquiryIDjTextField;
    private javax.swing.JScrollPane enquiryTablejScrollPane;
    private javax.swing.JTable enquiryTablejTable;
    private javax.swing.JPanel enquiryTypejPanel;
    private javax.swing.JPanel headerjPanel;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSearchAll;
    private javax.swing.JCheckBox jCheckBoxBenefits;
    private javax.swing.JCheckBox jCheckBoxDebt;
    private javax.swing.JCheckBox jCheckBoxDomestic;
    private javax.swing.JCheckBox jCheckBoxEmployment;
    private javax.swing.JCheckBox jCheckBoxHousing;
    private javax.swing.JCheckBox jCheckBoxOther;
    private javax.swing.JComboBox<String> jComboBoxEnquiryStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelClientID;
    private javax.swing.JLabel jLabelClientName;
    private javax.swing.JLabel jLabelNotes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextEnquiryNotes;
    private javax.swing.JTextField jTextFieldClientID;
    private javax.swing.JTextField jTextFieldClientName;
    private javax.swing.JTextField jTextFieldDate_Time;
    private javax.swing.JButton newjButton;
    private javax.swing.JPanel notesjPanel;
    private javax.swing.JButton savejButton;
    private javax.swing.JPanel searchjPanel;
    private javax.swing.JPanel windowjPanel;
    // End of variables declaration//GEN-END:variables
}
