/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residentsupportsystem;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author robbieoneill
 */
public class AdminManageWaitingList extends javax.swing.JFrame {
    int userLoggedIn;
    Client client = new Client();
    WaitingList waitingList = new WaitingList();
    public AdminManageWaitingList(int userID) {
        userLoggedIn = userID;
        initComponents();
        waitingList.setWaitingListTable(waitinglistTablejTable); //Rename this
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowjPanel = new javax.swing.JPanel();
        headerjPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clientDetailsjPanel = new javax.swing.JPanel();
        clientDetailsjLabel = new javax.swing.JLabel();
        clientFirstnamejLabel = new javax.swing.JLabel();
        clientFirstnamejTextField = new javax.swing.JTextField();
        clientMiddlenamejLabel = new javax.swing.JLabel();
        clientMiddlenamejTextField = new javax.swing.JTextField();
        clientLastnamejLabel = new javax.swing.JLabel();
        clientLastnamejTextField = new javax.swing.JTextField();
        clientGenderjLabel = new javax.swing.JLabel();
        clientDOBjLabel = new javax.swing.JLabel();
        clientDOBjTextField = new javax.swing.JTextField();
        clientEmailjLabel = new javax.swing.JLabel();
        clientEmailjTextField = new javax.swing.JTextField();
        clientTeljLabel = new javax.swing.JLabel();
        clientTeljTextField = new javax.swing.JTextField();
        clientMobjLabel = new javax.swing.JLabel();
        clientMobjTextField = new javax.swing.JTextField();
        clientAddr1jLabel = new javax.swing.JLabel();
        clientAddr1jTextField = new javax.swing.JTextField();
        clientAddr2jLabel = new javax.swing.JLabel();
        clientAddr2jTextField = new javax.swing.JTextField();
        clientPostcodejLabel = new javax.swing.JLabel();
        clientPostcodejTextField = new javax.swing.JTextField();
        clientNotesjLabel = new javax.swing.JLabel();
        clientNotesjScrollPanel = new javax.swing.JScrollPane();
        clientNotesjTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        clientIDjTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        clientGenderjTextField = new javax.swing.JTextField();
        clientTablejScrollPane = new javax.swing.JScrollPane();
        waitinglistTablejTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableAppointmentjTable = new javax.swing.JTable();
        enquiryDetailsjLabel = new javax.swing.JLabel();
        enquiryIDjLabel = new javax.swing.JLabel();
        adminIDjLabel = new javax.swing.JLabel();
        areajLabel = new javax.swing.JLabel();
        statusjLabel = new javax.swing.JLabel();
        enquiryDatejLabel = new javax.swing.JLabel();
        adminIDjTextField = new javax.swing.JTextField();
        areajTextField = new javax.swing.JTextField();
        statusjTextField = new javax.swing.JTextField();
        enquiryDatejTextField = new javax.swing.JTextField();
        enquiryNotesjLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        enquiryNotesjTextArea = new javax.swing.JTextArea();
        appointmentIDjLabel = new javax.swing.JLabel();
        appointmentDatejLabel = new javax.swing.JLabel();
        appointmentFromjLabel = new javax.swing.JLabel();
        appointmentTojLabel = new javax.swing.JLabel();
        appointmentCaseworkerjLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        appointmentDatejTextField = new javax.swing.JTextField();
        appointmentFromjTextField = new javax.swing.JTextField();
        appointmentTojTextField = new javax.swing.JTextField();
        caseworkerjTextField = new javax.swing.JTextField();
        appointmentNotesjLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        appointmentNotesjTextArea = new javax.swing.JTextArea();
        enquiryIDjTextField = new javax.swing.JTextField();
        appointmentIDjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowjPanel.setBackground(new java.awt.Color(51, 51, 51));

        headerjPanel.setBackground(new java.awt.Color(47, 54, 64));

        jLabel2.setBackground(new java.awt.Color(220, 221, 225));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 221, 225));
        jLabel2.setText("Manage Waiting List");

        javax.swing.GroupLayout headerjPanelLayout = new javax.swing.GroupLayout(headerjPanel);
        headerjPanel.setLayout(headerjPanelLayout);
        headerjPanelLayout.setHorizontalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerjPanelLayout.setVerticalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        clientDetailsjLabel.setText("Client Details");

        clientFirstnamejLabel.setText("Firstname");

        clientMiddlenamejLabel.setText("Middlename");

        clientLastnamejLabel.setText("Lastname");

        clientGenderjLabel.setText("Gender");

        clientDOBjLabel.setText("DOB");

        clientEmailjLabel.setText("Email");

        clientTeljLabel.setText("Telephone");

        clientMobjLabel.setText("Mobile");

        clientAddr1jLabel.setText("Addr 1");

        clientAddr1jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientAddr1jTextFieldActionPerformed(evt);
            }
        });

        clientAddr2jLabel.setText("Addr 2");

        clientPostcodejLabel.setText("Postcode");

        clientPostcodejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientPostcodejTextFieldActionPerformed(evt);
            }
        });

        clientNotesjLabel.setText("Notes");

        clientNotesjTextArea.setColumns(20);
        clientNotesjTextArea.setRows(5);
        clientNotesjScrollPanel.setViewportView(clientNotesjTextArea);

        jLabel1.setText("Client ID");

        clientIDjTextField.setEnabled(false);
        clientIDjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIDjTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientDetailsjPanelLayout = new javax.swing.GroupLayout(clientDetailsjPanel);
        clientDetailsjPanel.setLayout(clientDetailsjPanelLayout);
        clientDetailsjPanelLayout.setHorizontalGroup(
            clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                        .addComponent(clientDetailsjLabel)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clientIDjTextField))
                    .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(clientNotesjScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                        .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clientPostcodejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientAddr2jLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientAddr1jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientNotesjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientAddr2jTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clientPostcodejTextField)
                            .addComponent(clientAddr1jTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                        .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clientMobjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientTeljLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientEmailjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientDOBjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientGenderjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientLastnamejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientFirstnamejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientMiddlenamejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientMiddlenamejTextField)
                            .addComponent(clientFirstnamejTextField)
                            .addComponent(clientLastnamejTextField)
                            .addComponent(clientDOBjTextField)
                            .addComponent(clientEmailjTextField)
                            .addComponent(clientTeljTextField)
                            .addComponent(clientMobjTextField)
                            .addComponent(clientGenderjTextField))))
                .addContainerGap())
        );
        clientDetailsjPanelLayout.setVerticalGroup(
            clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDetailsjLabel)
                    .addComponent(jLabel1)
                    .addComponent(clientIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientFirstnamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientFirstnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientMiddlenamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientMiddlenamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientLastnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientLastnamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientGenderjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientGenderjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDOBjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientDOBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientEmailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientTeljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientTeljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientMobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientMobjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAddr1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientAddr1jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAddr2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientAddr2jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientPostcodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientPostcodejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientNotesjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientNotesjScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        waitinglistTablejTable.setBackground(new java.awt.Color(220, 221, 225));
        waitinglistTablejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "Lastname", "Area", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        waitinglistTablejTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                waitinglistTablejTableFocusGained(evt);
            }
        });
        waitinglistTablejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                waitinglistTablejTableMouseClicked(evt);
            }
        });
        clientTablejScrollPane.setViewportView(waitinglistTablejTable);

        availableAppointmentjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(availableAppointmentjTable);

        enquiryDetailsjLabel.setText("Enquiry Details");

        enquiryIDjLabel.setText("Enquiry ID");

        adminIDjLabel.setText("Admin");

        areajLabel.setText("Area");

        statusjLabel.setText("Status");

        enquiryDatejLabel.setText("Date");

        enquiryNotesjLabel.setText("Notes");

        enquiryNotesjTextArea.setColumns(20);
        enquiryNotesjTextArea.setRows(5);
        jScrollPane2.setViewportView(enquiryNotesjTextArea);

        appointmentIDjLabel.setText("Assign to Appointment");

        appointmentDatejLabel.setText("Date");

        appointmentFromjLabel.setText("From");

        appointmentTojLabel.setText("To");

        appointmentCaseworkerjLabel.setText("Caseworker");

        jButton2.setText("Assign Appointment");

        caseworkerjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseworkerjTextFieldActionPerformed(evt);
            }
        });

        appointmentNotesjLabel.setText("Notes");

        appointmentNotesjTextArea.setColumns(20);
        appointmentNotesjTextArea.setRows(5);
        jScrollPane3.setViewportView(appointmentNotesjTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(areajLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adminIDjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enquiryDetailsjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(statusjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(enquiryNotesjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                            .addComponent(enquiryDatejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(enquiryIDjLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(enquiryIDjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                .addComponent(statusjTextField)
                                .addComponent(areajTextField)
                                .addComponent(adminIDjTextField)
                                .addComponent(enquiryDatejTextField)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(appointmentIDjLabel)
                            .addGap(18, 18, 18)
                            .addComponent(appointmentIDjTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(appointmentDatejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(appointmentDatejTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(appointmentFromjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(appointmentFromjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(appointmentTojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(appointmentTojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(appointmentCaseworkerjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(caseworkerjTextField))))
                    .addComponent(appointmentNotesjLabel))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enquiryDetailsjLabel)
                    .addComponent(enquiryIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enquiryIDjLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminIDjLabel)
                    .addComponent(adminIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areajLabel)
                    .addComponent(areajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusjLabel)
                    .addComponent(statusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enquiryDatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enquiryDatejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enquiryNotesjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentIDjLabel)
                    .addComponent(appointmentIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentDatejLabel)
                    .addComponent(appointmentDatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentFromjLabel)
                    .addComponent(appointmentFromjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentTojLabel)
                    .addComponent(appointmentTojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentCaseworkerjLabel)
                    .addComponent(caseworkerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointmentNotesjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout windowjPanelLayout = new javax.swing.GroupLayout(windowjPanel);
        windowjPanel.setLayout(windowjPanelLayout);
        windowjPanelLayout.setHorizontalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(windowjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientDetailsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientTablejScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        windowjPanelLayout.setVerticalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowjPanelLayout.createSequentialGroup()
                .addComponent(headerjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientTablejScrollPane)
                    .addComponent(clientDetailsjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(windowjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientAddr1jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientAddr1jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientAddr1jTextFieldActionPerformed

    private void clientPostcodejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientPostcodejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientPostcodejTextFieldActionPerformed

    private void clientIDjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIDjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientIDjTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AdminDashboard(userLoggedIn).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void waitinglistTablejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waitinglistTablejTableMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_waitinglistTablejTableMouseClicked

    private void waitinglistTablejTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_waitinglistTablejTableFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_waitinglistTablejTableFocusGained

    private void caseworkerjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseworkerjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseworkerjTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminIDjLabel;
    private javax.swing.JTextField adminIDjTextField;
    private javax.swing.JLabel appointmentCaseworkerjLabel;
    private javax.swing.JLabel appointmentDatejLabel;
    private javax.swing.JTextField appointmentDatejTextField;
    private javax.swing.JLabel appointmentFromjLabel;
    private javax.swing.JTextField appointmentFromjTextField;
    private javax.swing.JLabel appointmentIDjLabel;
    private javax.swing.JTextField appointmentIDjTextField;
    private javax.swing.JLabel appointmentNotesjLabel;
    private javax.swing.JTextArea appointmentNotesjTextArea;
    private javax.swing.JLabel appointmentTojLabel;
    private javax.swing.JTextField appointmentTojTextField;
    private javax.swing.JLabel areajLabel;
    private javax.swing.JTextField areajTextField;
    private javax.swing.JTable availableAppointmentjTable;
    private javax.swing.JTextField caseworkerjTextField;
    private javax.swing.JLabel clientAddr1jLabel;
    private javax.swing.JTextField clientAddr1jTextField;
    private javax.swing.JLabel clientAddr2jLabel;
    private javax.swing.JTextField clientAddr2jTextField;
    private javax.swing.JLabel clientDOBjLabel;
    private javax.swing.JTextField clientDOBjTextField;
    private javax.swing.JLabel clientDetailsjLabel;
    private javax.swing.JPanel clientDetailsjPanel;
    private javax.swing.JLabel clientEmailjLabel;
    private javax.swing.JTextField clientEmailjTextField;
    private javax.swing.JLabel clientFirstnamejLabel;
    private javax.swing.JTextField clientFirstnamejTextField;
    private javax.swing.JLabel clientGenderjLabel;
    private javax.swing.JTextField clientGenderjTextField;
    private javax.swing.JTextField clientIDjTextField;
    private javax.swing.JLabel clientLastnamejLabel;
    private javax.swing.JTextField clientLastnamejTextField;
    private javax.swing.JLabel clientMiddlenamejLabel;
    private javax.swing.JTextField clientMiddlenamejTextField;
    private javax.swing.JLabel clientMobjLabel;
    private javax.swing.JTextField clientMobjTextField;
    private javax.swing.JLabel clientNotesjLabel;
    private javax.swing.JScrollPane clientNotesjScrollPanel;
    private javax.swing.JTextArea clientNotesjTextArea;
    private javax.swing.JLabel clientPostcodejLabel;
    private javax.swing.JTextField clientPostcodejTextField;
    private javax.swing.JScrollPane clientTablejScrollPane;
    private javax.swing.JLabel clientTeljLabel;
    private javax.swing.JTextField clientTeljTextField;
    private javax.swing.JLabel enquiryDatejLabel;
    private javax.swing.JTextField enquiryDatejTextField;
    private javax.swing.JLabel enquiryDetailsjLabel;
    private javax.swing.JLabel enquiryIDjLabel;
    private javax.swing.JTextField enquiryIDjTextField;
    private javax.swing.JLabel enquiryNotesjLabel;
    private javax.swing.JTextArea enquiryNotesjTextArea;
    private javax.swing.JPanel headerjPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel statusjLabel;
    private javax.swing.JTextField statusjTextField;
    private javax.swing.JTable waitinglistTablejTable;
    private javax.swing.JPanel windowjPanel;
    // End of variables declaration//GEN-END:variables
}
