/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residentsupportsystem;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TIT
 */
public class AdminManageAppointments extends javax.swing.JFrame {
    int userLoggedIn;
    User user = new User();
    Appointment appointment = new Appointment();
    
    
    public AdminManageAppointments(int userID) {
        userLoggedIn = userID;
        initComponents();
        //user.setUserTable(userTablejTable);
        int userAutoID = user.getUserAutoID();
        appointment.setInitAppointmentTable(customAppointmentjTable, "ALL", "ALL");
        nextSlotjTextField.setText("01/06/2020");
        //userIDjTextField.setText(String.valueOf(userAutoID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowjPanel = new javax.swing.JPanel();
        headerjPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userDetailsjPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        appointmentRoomjTextField = new javax.swing.JTextField();
        userGenderjLabel1 = new javax.swing.JLabel();
        appointmentEndjTextField = new javax.swing.JTextField();
        userFirstnamejLabel1 = new javax.swing.JLabel();
        appointmentIDjTextField = new javax.swing.JTextField();
        appointmentStartjTextField = new javax.swing.JTextField();
        userPostcodejLabel1 = new javax.swing.JLabel();
        userEmailjLabel1 = new javax.swing.JLabel();
        userMobjLabel1 = new javax.swing.JLabel();
        userTeljLabel1 = new javax.swing.JLabel();
        appointmentStatusjTextField = new javax.swing.JTextField();
        appointmentDatejTextField = new javax.swing.JTextField();
        userDetailsjLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        appointmentNotesjTextArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        enquiryIDjTextField = new javax.swing.JTextField();
        appointmentCaseworkerjTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        userGenderjLabel2 = new javax.swing.JLabel();
        userFirstnamejLabel2 = new javax.swing.JLabel();
        userEmailjLabel2 = new javax.swing.JLabel();
        adminNamejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        enquiryAreajTextField = new javax.swing.JTextField();
        enquiryStatusjTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        userGenderjLabel3 = new javax.swing.JLabel();
        clientTeljTextField = new javax.swing.JTextField();
        userFirstnamejLabel3 = new javax.swing.JLabel();
        clientIDjTextField = new javax.swing.JTextField();
        clientGenderjTextField = new javax.swing.JTextField();
        userEmailjLabel3 = new javax.swing.JLabel();
        userTeljLabel3 = new javax.swing.JLabel();
        clientNamejTextField = new javax.swing.JTextField();
        userDetailsjLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        clientDOBjTextField = new javax.swing.JTextField();
        userTeljLabel4 = new javax.swing.JLabel();
        clientMobjTextField = new javax.swing.JTextField();
        userTeljLabel5 = new javax.swing.JLabel();
        clientEmailjTextField = new javax.swing.JTextField();
        userTeljLabel6 = new javax.swing.JLabel();
        userTeljLabel7 = new javax.swing.JLabel();
        clientAddr1jTextField = new javax.swing.JTextField();
        clientPostcodejTextField = new javax.swing.JTextField();
        userTeljLabel8 = new javax.swing.JLabel();
        clientAddr2jTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customAppointmentjTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        searchjButton = new javax.swing.JButton();
        queryTypejComboBox = new javax.swing.JComboBox<>();
        queryConditionjTextField = new javax.swing.JTextField();
        canceljButton = new javax.swing.JButton();
        reschedulejButton = new javax.swing.JButton();
        nextSlotjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        searchAlljButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowjPanel.setBackground(new java.awt.Color(51, 51, 51));

        headerjPanel.setBackground(new java.awt.Color(47, 54, 64));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 221, 225));
        jLabel1.setText("Manage Appointments");

        javax.swing.GroupLayout headerjPanelLayout = new javax.swing.GroupLayout(headerjPanel);
        headerjPanel.setLayout(headerjPanelLayout);
        headerjPanelLayout.setHorizontalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerjPanelLayout.setVerticalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        userDetailsjPanel.setBackground(new java.awt.Color(113, 128, 147));

        appointmentRoomjTextField.setBackground(new java.awt.Color(220, 221, 225));
        appointmentRoomjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentRoomjTextFieldActionPerformed(evt);
            }
        });

        userGenderjLabel1.setText("Start");

        appointmentEndjTextField.setBackground(new java.awt.Color(220, 221, 225));

        userFirstnamejLabel1.setText("Date");

        appointmentIDjTextField.setBackground(new java.awt.Color(220, 221, 225));
        appointmentIDjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentIDjTextFieldActionPerformed(evt);
            }
        });

        appointmentStartjTextField.setBackground(new java.awt.Color(220, 221, 225));

        userPostcodejLabel1.setText("Notes");

        userEmailjLabel1.setText("End");

        userMobjLabel1.setText("Room");

        userTeljLabel1.setText("Status");

        appointmentStatusjTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentDatejTextField.setBackground(new java.awt.Color(220, 221, 225));

        userDetailsjLabel1.setText("Appointment ID");

        jLabel3.setText("Appoiontment Details");

        appointmentNotesjTextArea.setColumns(20);
        appointmentNotesjTextArea.setRows(5);
        jScrollPane2.setViewportView(appointmentNotesjTextArea);

        jLabel7.setText("Caseworker");

        jLabel9.setText("Enquiry");

        enquiryIDjTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentCaseworkerjTextField.setBackground(new java.awt.Color(220, 221, 225));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userDetailsjLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(appointmentIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(userTeljLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userEmailjLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userGenderjLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userFirstnamejLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userMobjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enquiryIDjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(appointmentStatusjTextField)
                            .addComponent(appointmentEndjTextField)
                            .addComponent(appointmentStartjTextField)
                            .addComponent(appointmentDatejTextField)
                            .addComponent(appointmentRoomjTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(appointmentCaseworkerjTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPostcodejLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userDetailsjLabel1)
                            .addComponent(appointmentIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userFirstnamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointmentDatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userGenderjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointmentStartjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userEmailjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointmentEndjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userTeljLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointmentStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userMobjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointmentRoomjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(appointmentCaseworkerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(enquiryIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(userPostcodejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addGap(11, 11, 11))))
        );

        userGenderjLabel2.setText("Area");

        userFirstnamejLabel2.setText("Admin");

        userEmailjLabel2.setText("Status");

        adminNamejTextField.setBackground(new java.awt.Color(220, 221, 225));

        jLabel4.setText("Enquiry Details");

        enquiryAreajTextField.setBackground(new java.awt.Color(220, 221, 225));
        enquiryAreajTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enquiryAreajTextFieldActionPerformed(evt);
            }
        });

        enquiryStatusjTextField.setBackground(new java.awt.Color(220, 221, 225));
        enquiryStatusjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enquiryStatusjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(userGenderjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(enquiryAreajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userEmailjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enquiryStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(userFirstnamejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(adminNamejTextField)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(233, 233, 233))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userFirstnamejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userEmailjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enquiryStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userGenderjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enquiryAreajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        userGenderjLabel3.setText("Gender");

        clientTeljTextField.setBackground(new java.awt.Color(220, 221, 225));

        userFirstnamejLabel3.setText("Name");

        clientIDjTextField.setBackground(new java.awt.Color(220, 221, 225));
        clientIDjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIDjTextFieldActionPerformed(evt);
            }
        });

        clientGenderjTextField.setBackground(new java.awt.Color(220, 221, 225));

        userEmailjLabel3.setText("DOB");

        userTeljLabel3.setText("Telephone");

        clientNamejTextField.setBackground(new java.awt.Color(220, 221, 225));

        userDetailsjLabel3.setText("Client ID");

        jLabel10.setText("Client Details");

        clientDOBjTextField.setBackground(new java.awt.Color(220, 221, 225));

        userTeljLabel4.setText("Mobile");

        clientMobjTextField.setBackground(new java.awt.Color(220, 221, 225));

        userTeljLabel5.setText("Email");

        clientEmailjTextField.setBackground(new java.awt.Color(220, 221, 225));

        userTeljLabel6.setText("Addr1");

        userTeljLabel7.setText("Addr2");

        clientAddr1jTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientPostcodejTextField.setBackground(new java.awt.Color(220, 221, 225));

        userTeljLabel8.setText("Postcode");

        clientAddr2jTextField.setBackground(new java.awt.Color(220, 221, 225));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userDetailsjLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(userTeljLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(userGenderjLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userFirstnamejLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userEmailjLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientGenderjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientDOBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientTeljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userTeljLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userTeljLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userTeljLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userTeljLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userTeljLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientAddr1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientPostcodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientMobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientAddr2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel10)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userDetailsjLabel3)
                            .addComponent(clientIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userFirstnamejLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userTeljLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userGenderjLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientGenderjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userTeljLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientAddr1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userEmailjLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(userTeljLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clientDOBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clientAddr2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientMobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userTeljLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTeljLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientTeljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTeljLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientPostcodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout userDetailsjPanelLayout = new javax.swing.GroupLayout(userDetailsjPanel);
        userDetailsjPanel.setLayout(userDetailsjPanelLayout);
        userDetailsjPanelLayout.setHorizontalGroup(
            userDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userDetailsjPanelLayout.setVerticalGroup(
            userDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userDetailsjPanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(120, 120, 120))
        );

        customAppointmentjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Start", "End", "Caseworker", "Client", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customAppointmentjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customAppointmentjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customAppointmentjTable);

        jLabel5.setText("Quick Actions");

        searchjButton.setText("Search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        queryTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search By:", "Status", "Caseworker ID", "Client ID", "Enquiry ID", "Enquiry Type", "Date", "Start", "End" }));

        queryConditionjTextField.setBackground(new java.awt.Color(220, 221, 225));

        canceljButton.setText("Cancel Appointment");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        reschedulejButton.setText("Reschedule to Next Avaiable Slot");
        reschedulejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reschedulejButtonActionPerformed(evt);
            }
        });

        nextSlotjTextField.setBackground(new java.awt.Color(220, 221, 225));

        jLabel6.setText("Next Available Slot: ");

        searchAlljButton.setText("Search All");
        searchAlljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAlljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(queryTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(queryConditionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(canceljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reschedulejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(searchjButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchAlljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nextSlotjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queryTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryConditionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchAlljButton)
                .addGap(18, 18, 18)
                .addComponent(canceljButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reschedulejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextSlotjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout windowjPanelLayout = new javax.swing.GroupLayout(windowjPanel);
        windowjPanel.setLayout(windowjPanelLayout);
        windowjPanelLayout.setHorizontalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(windowjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userDetailsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(windowjPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backjButton)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        windowjPanelLayout.setVerticalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowjPanelLayout.createSequentialGroup()
                .addComponent(headerjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userDetailsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(windowjPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backjButton))
                    .addComponent(jScrollPane1))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowjPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        new AdminDashboard(userLoggedIn).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backjButtonActionPerformed

    private void appointmentIDjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentIDjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentIDjTextFieldActionPerformed

    private void appointmentRoomjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentRoomjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentRoomjTextFieldActionPerformed

    private void clientIDjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIDjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientIDjTextFieldActionPerformed

    private void enquiryAreajTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enquiryAreajTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enquiryAreajTextFieldActionPerformed

    private void enquiryStatusjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enquiryStatusjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enquiryStatusjTextFieldActionPerformed

    private void customAppointmentjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customAppointmentjTableMouseClicked
        DefaultTableModel customAppointmentTable = (DefaultTableModel)customAppointmentjTable.getModel();
        int selectedRow = customAppointmentjTable.getSelectedRow();
        String selectedUserPointer = (customAppointmentjTable.getValueAt(selectedRow, 0).toString());
        int selectedAppointmentID = Integer.parseInt(selectedUserPointer);			
        
        List appointmentArrayList = appointment.setAllAppointmentDetails(selectedAppointmentID);
        System.out.println(appointmentArrayList);
        //appointmentID
                //appointmentDate
                //apointmentStart
                //appointmentEnd
                //appointmentStatus
                //appointmentRoom
                //appointmentNotes
                //userFirstname
                //userLastname (JOIN)
                //enquiryID
                //enquiryArea
                //enquiryStatus
                //clientID
                //clientFirstname
                //clientLastname (JOIN)
                //clientGender
                //clientDOB
                //clientTelNumber
                //clientMobNumber
                //clientEmail
                //clientAddr1
                //clientAddr2
                //clientPostcode
                
        appointmentIDjTextField.setText(appointmentArrayList.get(0).toString());
        appointmentDatejTextField.setText(appointmentArrayList.get(1).toString());
        appointmentStartjTextField.setText(appointmentArrayList.get(2).toString());
        appointmentEndjTextField.setText(appointmentArrayList.get(3).toString());
        appointmentStatusjTextField.setText(appointmentArrayList.get(4).toString());
        appointmentRoomjTextField.setText(appointmentArrayList.get(5).toString());
        appointmentNotesjTextArea.setText(appointmentArrayList.get(6).toString());
        appointmentCaseworkerjTextField.setText(appointmentArrayList.get(7).toString());
        enquiryIDjTextField.setText(appointmentArrayList.get(8).toString());
        enquiryAreajTextField.setText(appointmentArrayList.get(9).toString());
        enquiryStatusjTextField.setText(appointmentArrayList.get(10).toString());
        clientIDjTextField.setText(appointmentArrayList.get(11).toString());
        clientNamejTextField.setText(appointmentArrayList.get(12).toString());
        clientGenderjTextField.setText(appointmentArrayList.get(13).toString());
        clientDOBjTextField.setText(appointmentArrayList.get(14).toString());
        clientTeljTextField.setText(appointmentArrayList.get(15).toString());
        clientMobjTextField.setText(appointmentArrayList.get(16).toString());
        clientEmailjTextField.setText(appointmentArrayList.get(17).toString());
        clientAddr1jTextField.setText(appointmentArrayList.get(18).toString());
        clientAddr2jTextField.setText(appointmentArrayList.get(19).toString());
        clientPostcodejTextField.setText(appointmentArrayList.get(20).toString());

        
        
    }//GEN-LAST:event_customAppointmentjTableMouseClicked

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed

       
        String whereTerm = queryTypejComboBox.getSelectedItem().toString();
        String whereCondition = queryConditionjTextField.getText();
        
        if (whereTerm.equals("Search By:")){
            System.out.println("NO SEARCH TERM CHOSEN");
            JOptionPane.showMessageDialog(rootPane,"Please Select Search Term","Warning", 2);
        }else{
            if(whereTerm.equals("Status")){
                whereTerm = "tbl_appointment.appointmentStatus";
            }else if(whereTerm.equals("Caseworker ID")){
                whereTerm = "tbl_appointment.appointmentCaseworkerID";
            }else if(whereTerm.equals("Client ID")){
                whereTerm = "tbl_client.clientID";
            }else if(whereTerm.equals("Enquiry ID")){
                whereTerm = "tbl_appointment.appointmentEnquiryID";
            }else if(whereTerm.equals("Enquiry Type")){
                whereTerm = "tbl_enquiry.enquiryArea";
            }else if(whereTerm.equals("Date")){
                whereTerm = "tbl_appointment.appointmentDate";
            }else if(whereTerm.equals("Start")){
                whereTerm = "tbl_appointment.appointmentStartTime";
            }else if(whereTerm.equals("End")){
                whereTerm = "tbl_appointment.appointmentEndTime";
            }else{
                System.out.println("NO SEARCH TERM SUITABLE");
            JOptionPane.showMessageDialog(rootPane,"Error, Please Try Again","Error", 2);
            }
            appointment.setCustomAppointmentTable(customAppointmentjTable, whereTerm, whereCondition);
        }
        
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void searchAlljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAlljButtonActionPerformed
        appointment.setInitAppointmentTable(customAppointmentjTable, "ALL", "ALL");
    }//GEN-LAST:event_searchAlljButtonActionPerformed

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        String appointmentID = appointmentIDjTextField.getText();
        appointment.cancelAppointment(appointmentID);
        JOptionPane.showMessageDialog(rootPane,"Appointment Cancelled","Info", 2);
    }//GEN-LAST:event_canceljButtonActionPerformed

    private void reschedulejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reschedulejButtonActionPerformed
        String appointmentID = appointmentIDjTextField.getText();
        appointment.cancelAppointment(appointmentID);
        JOptionPane.showMessageDialog(rootPane,"Appointment Rescheduled","Info", 2);
    }//GEN-LAST:event_reschedulejButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminNamejTextField;
    private javax.swing.JTextField appointmentCaseworkerjTextField;
    private javax.swing.JTextField appointmentDatejTextField;
    private javax.swing.JTextField appointmentEndjTextField;
    private javax.swing.JTextField appointmentIDjTextField;
    private javax.swing.JTextArea appointmentNotesjTextArea;
    private javax.swing.JTextField appointmentRoomjTextField;
    private javax.swing.JTextField appointmentStartjTextField;
    private javax.swing.JTextField appointmentStatusjTextField;
    private javax.swing.JButton backjButton;
    private javax.swing.JButton canceljButton;
    private javax.swing.JTextField clientAddr1jTextField;
    private javax.swing.JTextField clientAddr2jTextField;
    private javax.swing.JTextField clientDOBjTextField;
    private javax.swing.JTextField clientEmailjTextField;
    private javax.swing.JTextField clientGenderjTextField;
    private javax.swing.JTextField clientIDjTextField;
    private javax.swing.JTextField clientMobjTextField;
    private javax.swing.JTextField clientNamejTextField;
    private javax.swing.JTextField clientPostcodejTextField;
    private javax.swing.JTextField clientTeljTextField;
    private javax.swing.JTable customAppointmentjTable;
    private javax.swing.JTextField enquiryAreajTextField;
    private javax.swing.JTextField enquiryIDjTextField;
    private javax.swing.JTextField enquiryStatusjTextField;
    private javax.swing.JPanel headerjPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nextSlotjTextField;
    private javax.swing.JTextField queryConditionjTextField;
    private javax.swing.JComboBox<String> queryTypejComboBox;
    private javax.swing.JButton reschedulejButton;
    private javax.swing.JButton searchAlljButton;
    private javax.swing.JButton searchjButton;
    private javax.swing.JLabel userDetailsjLabel1;
    private javax.swing.JLabel userDetailsjLabel3;
    private javax.swing.JPanel userDetailsjPanel;
    private javax.swing.JLabel userEmailjLabel1;
    private javax.swing.JLabel userEmailjLabel2;
    private javax.swing.JLabel userEmailjLabel3;
    private javax.swing.JLabel userFirstnamejLabel1;
    private javax.swing.JLabel userFirstnamejLabel2;
    private javax.swing.JLabel userFirstnamejLabel3;
    private javax.swing.JLabel userGenderjLabel1;
    private javax.swing.JLabel userGenderjLabel2;
    private javax.swing.JLabel userGenderjLabel3;
    private javax.swing.JLabel userMobjLabel1;
    private javax.swing.JLabel userPostcodejLabel1;
    private javax.swing.JLabel userTeljLabel1;
    private javax.swing.JLabel userTeljLabel3;
    private javax.swing.JLabel userTeljLabel4;
    private javax.swing.JLabel userTeljLabel5;
    private javax.swing.JLabel userTeljLabel6;
    private javax.swing.JLabel userTeljLabel7;
    private javax.swing.JLabel userTeljLabel8;
    private javax.swing.JPanel windowjPanel;
    // End of variables declaration//GEN-END:variables
}
