/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residentsupportsystem;

/**
 *
 * @author robbieoneill
 */
public class AdminDashboard extends javax.swing.JFrame {
    User user = new User();
    Client client = new Client();
    int userLoggedIn;
    
    
    public AdminDashboard(int userID){
        userLoggedIn = userID; 
        initComponents();
        test.setText(Integer.toString(userLoggedIn));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        manageCaseworkersjButton = new javax.swing.JButton();
        manageClientsjButton = new javax.swing.JButton();
        logOutjButton = new javax.swing.JButton();
        manageInquirysjButton = new javax.swing.JButton();
        manageAppointmentsjButton = new javax.swing.JButton();
        manageDetailsjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        clientCountjPanel = new javax.swing.JPanel();
        clientCountHeaderjLabel = new javax.swing.JLabel();
        clientCountjLabel = new javax.swing.JLabel();
        caseworkerCountjPanel = new javax.swing.JPanel();
        caseworkerCountHeaderjLabel = new javax.swing.JLabel();
        caseworkerCountjLabel = new javax.swing.JLabel();
        appointmentCountjPanel = new javax.swing.JPanel();
        appointmentCountHeaderjLabel = new javax.swing.JLabel();
        appointmentCountjLabel = new javax.swing.JLabel();
        activeCasesCountjPanel = new javax.swing.JPanel();
        activeCasesCountHeaderjLabel = new javax.swing.JLabel();
        activeCasesCountjLabel = new javax.swing.JLabel();
        test = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(113, 128, 147));

        jPanel2.setBackground(new java.awt.Color(47, 54, 64));

        manageCaseworkersjButton.setText("Manage Caseworkers");
        manageCaseworkersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCaseworkersjButtonActionPerformed(evt);
            }
        });

        manageClientsjButton.setText("Manage Clients");
        manageClientsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageClientsjButtonActionPerformed(evt);
            }
        });

        logOutjButton.setBackground(new java.awt.Color(153, 0, 153));
        logOutjButton.setText("Log Out");
        logOutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutjButtonActionPerformed(evt);
            }
        });

        manageInquirysjButton.setText("Manage Inquirys");
        manageInquirysjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInquirysjButtonActionPerformed(evt);
            }
        });

        manageAppointmentsjButton.setText("Manage Appointments");
        manageAppointmentsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAppointmentsjButtonActionPerformed(evt);
            }
        });

        manageDetailsjButton.setText("Manage Details");
        manageDetailsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDetailsjButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Manage Wating List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageDetailsjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageAppointmentsjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(manageInquirysjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageClientsjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageCaseworkersjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageClientsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageCaseworkersjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageInquirysjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageAppointmentsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageDetailsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );

        jPanel3.setBackground(new java.awt.Color(47, 54, 64));

        clientCountjPanel.setBackground(new java.awt.Color(113, 128, 147));
        clientCountjPanel.setPreferredSize(new java.awt.Dimension(175, 40));

        clientCountHeaderjLabel.setText("               Clients");

        clientCountjLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        clientCountjLabel.setText("Null");

        javax.swing.GroupLayout clientCountjPanelLayout = new javax.swing.GroupLayout(clientCountjPanel);
        clientCountjPanel.setLayout(clientCountjPanelLayout);
        clientCountjPanelLayout.setHorizontalGroup(
            clientCountjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientCountHeaderjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(clientCountjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        clientCountjPanelLayout.setVerticalGroup(
            clientCountjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientCountjPanelLayout.createSequentialGroup()
                .addComponent(clientCountHeaderjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clientCountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        caseworkerCountjPanel.setBackground(new java.awt.Color(113, 128, 147));
        caseworkerCountjPanel.setPreferredSize(new java.awt.Dimension(175, 40));

        caseworkerCountHeaderjLabel.setText("           Case Workers");

        caseworkerCountjLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        caseworkerCountjLabel.setText("Null");

        javax.swing.GroupLayout caseworkerCountjPanelLayout = new javax.swing.GroupLayout(caseworkerCountjPanel);
        caseworkerCountjPanel.setLayout(caseworkerCountjPanelLayout);
        caseworkerCountjPanelLayout.setHorizontalGroup(
            caseworkerCountjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(caseworkerCountHeaderjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(caseworkerCountjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        caseworkerCountjPanelLayout.setVerticalGroup(
            caseworkerCountjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caseworkerCountjPanelLayout.createSequentialGroup()
                .addComponent(caseworkerCountHeaderjLabel)
                .addGap(18, 18, 18)
                .addComponent(caseworkerCountjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        appointmentCountjPanel.setBackground(new java.awt.Color(113, 128, 147));
        appointmentCountjPanel.setPreferredSize(new java.awt.Dimension(175, 40));

        appointmentCountHeaderjLabel.setText("  Upcoming Appointments");

        appointmentCountjLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        appointmentCountjLabel.setText("Null");

        javax.swing.GroupLayout appointmentCountjPanelLayout = new javax.swing.GroupLayout(appointmentCountjPanel);
        appointmentCountjPanel.setLayout(appointmentCountjPanelLayout);
        appointmentCountjPanelLayout.setHorizontalGroup(
            appointmentCountjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appointmentCountHeaderjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(appointmentCountjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        appointmentCountjPanelLayout.setVerticalGroup(
            appointmentCountjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentCountjPanelLayout.createSequentialGroup()
                .addComponent(appointmentCountHeaderjLabel)
                .addGap(18, 18, 18)
                .addComponent(appointmentCountjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        activeCasesCountjPanel.setBackground(new java.awt.Color(113, 128, 147));
        activeCasesCountjPanel.setPreferredSize(new java.awt.Dimension(175, 40));

        activeCasesCountHeaderjLabel.setText("            Active Cases");

        activeCasesCountjLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        activeCasesCountjLabel.setText("Null");

        javax.swing.GroupLayout activeCasesCountjPanelLayout = new javax.swing.GroupLayout(activeCasesCountjPanel);
        activeCasesCountjPanel.setLayout(activeCasesCountjPanelLayout);
        activeCasesCountjPanelLayout.setHorizontalGroup(
            activeCasesCountjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activeCasesCountHeaderjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(activeCasesCountjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        activeCasesCountjPanelLayout.setVerticalGroup(
            activeCasesCountjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activeCasesCountjPanelLayout.createSequentialGroup()
                .addComponent(activeCasesCountHeaderjLabel)
                .addGap(18, 18, 18)
                .addComponent(activeCasesCountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(clientCountjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(caseworkerCountjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(appointmentCountjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(activeCasesCountjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activeCasesCountjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, Short.MAX_VALUE)
            .addComponent(caseworkerCountjPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
            .addComponent(clientCountjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
            .addComponent(appointmentCountjPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );

        test.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        test.setText("Admin Dashboard, Welcome  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(test))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(test)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutjButtonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_logOutjButtonActionPerformed

    private void manageInquirysjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInquirysjButtonActionPerformed
        new AdminManageInquirys(userLoggedIn).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_manageInquirysjButtonActionPerformed

    private void manageCaseworkersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCaseworkersjButtonActionPerformed
        new AdminManageUsers(userLoggedIn).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageCaseworkersjButtonActionPerformed

    private void manageAppointmentsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAppointmentsjButtonActionPerformed
       
    }//GEN-LAST:event_manageAppointmentsjButtonActionPerformed

    private void manageClientsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageClientsjButtonActionPerformed
        new AdminManageClients(userLoggedIn).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageClientsjButtonActionPerformed

    private void manageDetailsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDetailsjButtonActionPerformed
        new AllUsersManageDetails(userLoggedIn).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageDetailsjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AdminManageWaitingList(userLoggedIn).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeCasesCountHeaderjLabel;
    private javax.swing.JLabel activeCasesCountjLabel;
    private javax.swing.JPanel activeCasesCountjPanel;
    private javax.swing.JLabel appointmentCountHeaderjLabel;
    private javax.swing.JLabel appointmentCountjLabel;
    private javax.swing.JPanel appointmentCountjPanel;
    private javax.swing.JLabel caseworkerCountHeaderjLabel;
    private javax.swing.JLabel caseworkerCountjLabel;
    private javax.swing.JPanel caseworkerCountjPanel;
    private javax.swing.JLabel clientCountHeaderjLabel;
    private javax.swing.JLabel clientCountjLabel;
    private javax.swing.JPanel clientCountjPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logOutjButton;
    private javax.swing.JButton manageAppointmentsjButton;
    private javax.swing.JButton manageCaseworkersjButton;
    private javax.swing.JButton manageClientsjButton;
    private javax.swing.JButton manageDetailsjButton;
    private javax.swing.JButton manageInquirysjButton;
    private javax.swing.JLabel test;
    // End of variables declaration//GEN-END:variables
}
