/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residentsupportsystem;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author robbieoneill
 */
public class AdminManageClients extends javax.swing.JFrame {
    int userLoggedIn;
    Client client = new Client();
    public AdminManageClients(int userID) {
        userLoggedIn = userID;
        initComponents();
        client.setClientTable(clientTablejTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowjPanel = new javax.swing.JPanel();
        headerjPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clientDetailsjPanel = new javax.swing.JPanel();
        clientDetailsjLabel = new javax.swing.JLabel();
        clientFirstnamejLabel = new javax.swing.JLabel();
        clientFirstnamejTextField = new javax.swing.JTextField();
        clientMiddlenamejLabel = new javax.swing.JLabel();
        clientMiddlenamejTextField = new javax.swing.JTextField();
        clientLastnamejLabel = new javax.swing.JLabel();
        clientLastnamejTextField = new javax.swing.JTextField();
        clientGenderjLabel = new javax.swing.JLabel();
        clientGenderjComboBox = new javax.swing.JComboBox<>();
        clientDOBjLabel = new javax.swing.JLabel();
        clientDOBjTextField = new javax.swing.JTextField();
        clientEmailjLabel = new javax.swing.JLabel();
        clientEmailjTextField = new javax.swing.JTextField();
        clientTeljLabel = new javax.swing.JLabel();
        clientTeljTextField = new javax.swing.JTextField();
        clientMobjLabel = new javax.swing.JLabel();
        clientMobjTextField = new javax.swing.JTextField();
        clientAddr1jLabel = new javax.swing.JLabel();
        clientAddr1jTextField = new javax.swing.JTextField();
        clientAddr2jLabel = new javax.swing.JLabel();
        clientAddr2jTextField = new javax.swing.JTextField();
        clientPostcodejLabel = new javax.swing.JLabel();
        clientPostcodejTextField = new javax.swing.JTextField();
        clientNotesjLabel = new javax.swing.JLabel();
        clientNotesjScrollPanel = new javax.swing.JScrollPane();
        clientNotesjTextArea = new javax.swing.JTextArea();
        addClientjButton = new javax.swing.JButton();
        saveClientjButton = new javax.swing.JButton();
        deleteClientjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        clientIDjTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        clientTablejScrollPane = new javax.swing.JScrollPane();
        clientTablejTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowjPanel.setBackground(new java.awt.Color(51, 51, 51));

        headerjPanel.setBackground(new java.awt.Color(47, 54, 64));

        jLabel2.setBackground(new java.awt.Color(220, 221, 225));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 221, 225));
        jLabel2.setText("Manage Clients");

        javax.swing.GroupLayout headerjPanelLayout = new javax.swing.GroupLayout(headerjPanel);
        headerjPanel.setLayout(headerjPanelLayout);
        headerjPanelLayout.setHorizontalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerjPanelLayout.setVerticalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        clientDetailsjPanel.setBackground(new java.awt.Color(113, 128, 147));

        clientDetailsjLabel.setText("Client Details");

        clientFirstnamejLabel.setText("Firstname");

        clientFirstnamejTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientMiddlenamejLabel.setText("Middlename");

        clientMiddlenamejTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientLastnamejLabel.setText("Lastname");

        clientLastnamejTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientGenderjLabel.setText("Gender");

        clientGenderjComboBox.setBackground(new java.awt.Color(220, 221, 225));
        clientGenderjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client Gender:", "Male", "Female", "Other" }));

        clientDOBjLabel.setText("DOB");

        clientDOBjTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientEmailjLabel.setText("Email");

        clientEmailjTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientTeljLabel.setText("Telephone");

        clientTeljTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientMobjLabel.setText("Mobile");

        clientMobjTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientAddr1jLabel.setText("Addr 1");

        clientAddr1jTextField.setBackground(new java.awt.Color(220, 221, 225));
        clientAddr1jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientAddr1jTextFieldActionPerformed(evt);
            }
        });

        clientAddr2jLabel.setText("Addr 2");

        clientAddr2jTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientPostcodejLabel.setText("Postcode");

        clientPostcodejTextField.setBackground(new java.awt.Color(220, 221, 225));
        clientPostcodejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientPostcodejTextFieldActionPerformed(evt);
            }
        });

        clientNotesjLabel.setText("Notes");

        clientNotesjTextArea.setEditable(false);
        clientNotesjTextArea.setBackground(new java.awt.Color(220, 221, 225));
        clientNotesjTextArea.setColumns(20);
        clientNotesjTextArea.setRows(5);
        clientNotesjScrollPanel.setViewportView(clientNotesjTextArea);

        addClientjButton.setBackground(new java.awt.Color(102, 102, 102));
        addClientjButton.setForeground(new java.awt.Color(25, 42, 86));
        addClientjButton.setText("Add");
        addClientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientjButtonActionPerformed(evt);
            }
        });

        saveClientjButton.setBackground(new java.awt.Color(102, 102, 102));
        saveClientjButton.setForeground(new java.awt.Color(25, 42, 86));
        saveClientjButton.setText("Save");
        saveClientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveClientjButtonActionPerformed(evt);
            }
        });

        deleteClientjButton.setBackground(new java.awt.Color(102, 102, 102));
        deleteClientjButton.setForeground(new java.awt.Color(194, 54, 22));
        deleteClientjButton.setText("Delete");
        deleteClientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClientjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Client ID");

        clientIDjTextField.setBackground(new java.awt.Color(220, 221, 225));
        clientIDjTextField.setEnabled(false);
        clientIDjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIDjTextFieldActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(25, 42, 86));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientDetailsjPanelLayout = new javax.swing.GroupLayout(clientDetailsjPanel);
        clientDetailsjPanel.setLayout(clientDetailsjPanelLayout);
        clientDetailsjPanelLayout.setHorizontalGroup(
            clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveClientjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addClientjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteClientjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                        .addComponent(clientDetailsjLabel)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clientIDjTextField))
                    .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(clientNotesjScrollPanel)
                    .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                        .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clientPostcodejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientAddr2jLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientAddr1jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientNotesjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientAddr2jTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clientPostcodejTextField)
                            .addComponent(clientAddr1jTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                        .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clientMobjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientTeljLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientEmailjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientDOBjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientGenderjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientLastnamejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientFirstnamejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientMiddlenamejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientMiddlenamejTextField)
                            .addComponent(clientFirstnamejTextField)
                            .addComponent(clientLastnamejTextField)
                            .addComponent(clientDOBjTextField)
                            .addComponent(clientEmailjTextField)
                            .addComponent(clientTeljTextField)
                            .addComponent(clientMobjTextField)
                            .addComponent(clientGenderjComboBox, 0, 176, Short.MAX_VALUE))))
                .addContainerGap())
        );
        clientDetailsjPanelLayout.setVerticalGroup(
            clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDetailsjLabel)
                    .addComponent(jLabel1)
                    .addComponent(clientIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientFirstnamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientFirstnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientMiddlenamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientMiddlenamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientLastnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientLastnamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientGenderjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientGenderjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDOBjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientDOBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientEmailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientTeljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientTeljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientMobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientMobjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAddr1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientAddr1jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAddr2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientAddr2jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientPostcodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientPostcodejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientNotesjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientNotesjScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addClientjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveClientjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteClientjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clientTablejTable.setBackground(new java.awt.Color(220, 221, 225));
        clientTablejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client ID", "Firstname", "Lastname", "DOB", "Telephone", "Mobile", "Postcode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientTablejTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientTablejTableFocusGained(evt);
            }
        });
        clientTablejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTablejTableMouseClicked(evt);
            }
        });
        clientTablejScrollPane.setViewportView(clientTablejTable);

        javax.swing.GroupLayout windowjPanelLayout = new javax.swing.GroupLayout(windowjPanel);
        windowjPanel.setLayout(windowjPanelLayout);
        windowjPanelLayout.setHorizontalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(windowjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientDetailsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientTablejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        windowjPanelLayout.setVerticalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowjPanelLayout.createSequentialGroup()
                .addComponent(headerjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(windowjPanelLayout.createSequentialGroup()
                        .addComponent(clientDetailsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(clientTablejScrollPane))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientjButtonActionPerformed
        String clientAutoID=String.valueOf(client.getAutoClientID());
        clientIDjTextField.setText(clientAutoID);
        clientFirstnamejTextField.setText("");
        clientMiddlenamejTextField.setText("");
        clientLastnamejTextField.setText("");
        clientGenderjComboBox.setSelectedItem("Client Gender:");
        clientDOBjTextField.setText("");
        clientEmailjTextField.setText("");
        clientTeljTextField.setText("");
        clientMobjTextField.setText("");
        clientAddr1jTextField.setText("");
        clientAddr2jTextField.setText("");
        clientPostcodejTextField.setText("");
        clientNotesjTextArea.setText("");
        System.out.println("TEXT FIELDS WIPED");
    }//GEN-LAST:event_addClientjButtonActionPerformed

    private void saveClientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveClientjButtonActionPerformed

        String enteredClientID = clientIDjTextField.getText();
        String enteredClientFirstname = clientFirstnamejTextField.getText();
        String enteredClientMiddlename = clientMiddlenamejTextField.getText();
        String enteredClientLastname = clientLastnamejTextField.getText();
        String enteredClientGender = clientGenderjComboBox.getSelectedItem().toString();
        String enteredClientDOB = clientDOBjTextField.getText();
        String enteredClientEmail = clientEmailjTextField.getText();
        String enteredClientTelephone = clientTeljTextField.getText();
        String enteredClientMob = clientMobjTextField.getText();
        String enteredClientAddr1 = clientAddr1jTextField.getText();
        String enteredClientAddr2 = clientAddr2jTextField.getText();
        String enteredClientPostcode = clientPostcodejTextField.getText();
        String enteredClientNotes = clientNotesjTextArea.getText();
        
        if (enteredClientGender.equals("Client Gender:")){
            System.out.println("CLIENT GENDER NOT SET");
            JOptionPane.showMessageDialog(rootPane,"Please Select Gender","Warning", 2);
        }
        else if( 
                enteredClientID.trim().equals("") ||
                enteredClientFirstname.trim().equals("") ||
                enteredClientLastname.trim().equals("") ||
                enteredClientDOB.trim().equals("") ||
                enteredClientEmail.trim().equals("") ||
                enteredClientTelephone.trim().equals("") ||
                enteredClientMob.trim().equals("") ||
                enteredClientAddr1.trim().equals("") ||
                enteredClientPostcode.trim().equals("")
                ){
            JOptionPane.showMessageDialog(rootPane,"Please Ensure All Required User Details are Entered","Warning", 2);
        }
        else{
           if(client.insertClient(
                enteredClientID,
                enteredClientFirstname,
                enteredClientMiddlename,
                enteredClientLastname,
                enteredClientGender,
                enteredClientDOB,
                enteredClientEmail,
                enteredClientTelephone,
                enteredClientMob,
                enteredClientAddr1,
                enteredClientAddr2,
                enteredClientPostcode,
                enteredClientNotes
            )){
                System.out.println("DATABASE UPDATED");
            }
            else{
                System.out.println("DATABASE NOT UPDATED");
            } 
        }
        
        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_saveClientjButtonActionPerformed

    private void deleteClientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClientjButtonActionPerformed
        String clientID =  clientIDjTextField.getText();
        if(client.deleteClient(clientID)){
            System.out.println("CLIENT DELETED");
        }else{
            System.out.println("DELETE FAILED");
        }
    }//GEN-LAST:event_deleteClientjButtonActionPerformed

    private void clientAddr1jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientAddr1jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientAddr1jTextFieldActionPerformed

    private void clientPostcodejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientPostcodejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientPostcodejTextFieldActionPerformed

    private void clientIDjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIDjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientIDjTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AdminDashboard(userLoggedIn).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clientTablejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTablejTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel clientTable = (DefaultTableModel)clientTablejTable.getModel();
        int selectedRow = clientTablejTable.getSelectedRow();
        String selectedUserPointer = (clientTable.getValueAt(selectedRow, 0).toString());
        int selectedUserID = Integer.parseInt(selectedUserPointer);			
        List resultSetArrayList = client.setClientDetails(selectedUserID);
        clientIDjTextField.setText(resultSetArrayList.get(0).toString());
        clientFirstnamejTextField.setText(resultSetArrayList.get(1).toString());
        clientMiddlenamejTextField.setText(resultSetArrayList.get(2).toString());
        clientLastnamejTextField.setText(resultSetArrayList.get(3).toString());
        clientGenderjComboBox.setSelectedItem(resultSetArrayList.get(4).toString());
        clientDOBjTextField.setText(resultSetArrayList.get(5).toString());
        clientEmailjTextField.setText(resultSetArrayList.get(6).toString());
        clientTeljTextField.setText(resultSetArrayList.get(7).toString());
        clientMobjTextField.setText(resultSetArrayList.get(8).toString());
        clientAddr1jTextField.setText(resultSetArrayList.get(9).toString());
        clientAddr2jTextField.setText(resultSetArrayList.get(10).toString());
        clientPostcodejTextField.setText(resultSetArrayList.get(11).toString());
        clientNotesjTextArea.setText(resultSetArrayList.get(12).toString());

    }//GEN-LAST:event_clientTablejTableMouseClicked

    private void clientTablejTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientTablejTableFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_clientTablejTableFocusGained

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientjButton;
    private javax.swing.JLabel clientAddr1jLabel;
    private javax.swing.JTextField clientAddr1jTextField;
    private javax.swing.JLabel clientAddr2jLabel;
    private javax.swing.JTextField clientAddr2jTextField;
    private javax.swing.JLabel clientDOBjLabel;
    private javax.swing.JTextField clientDOBjTextField;
    private javax.swing.JLabel clientDetailsjLabel;
    private javax.swing.JPanel clientDetailsjPanel;
    private javax.swing.JLabel clientEmailjLabel;
    private javax.swing.JTextField clientEmailjTextField;
    private javax.swing.JLabel clientFirstnamejLabel;
    private javax.swing.JTextField clientFirstnamejTextField;
    private javax.swing.JComboBox<String> clientGenderjComboBox;
    private javax.swing.JLabel clientGenderjLabel;
    private javax.swing.JTextField clientIDjTextField;
    private javax.swing.JLabel clientLastnamejLabel;
    private javax.swing.JTextField clientLastnamejTextField;
    private javax.swing.JLabel clientMiddlenamejLabel;
    private javax.swing.JTextField clientMiddlenamejTextField;
    private javax.swing.JLabel clientMobjLabel;
    private javax.swing.JTextField clientMobjTextField;
    private javax.swing.JLabel clientNotesjLabel;
    private javax.swing.JScrollPane clientNotesjScrollPanel;
    private javax.swing.JTextArea clientNotesjTextArea;
    private javax.swing.JLabel clientPostcodejLabel;
    private javax.swing.JTextField clientPostcodejTextField;
    private javax.swing.JScrollPane clientTablejScrollPane;
    private javax.swing.JTable clientTablejTable;
    private javax.swing.JLabel clientTeljLabel;
    private javax.swing.JTextField clientTeljTextField;
    private javax.swing.JButton deleteClientjButton;
    private javax.swing.JPanel headerjPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton saveClientjButton;
    private javax.swing.JPanel windowjPanel;
    // End of variables declaration//GEN-END:variables
}
