/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residentsupportsystem;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author robbieoneill
 */
public class CaseworkerManageAppointments extends javax.swing.JFrame {

    int userLoggedIn;
    Case caseInstance = new Case();
    Appointment appointmentConnectionInstance = new Appointment();
    /**
     * Creates new form caseworkerManageCases
     */
    public CaseworkerManageAppointments(int userID) {
        userLoggedIn = userID;
        initComponents();
        
        caseInstance.setCaseTable(caseTablejTable, "ALL CASES");
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowjPanel = new javax.swing.JPanel();
        headerjPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        casesjPanel = new javax.swing.JPanel();
        filterjPanel = new javax.swing.JPanel();
        searchAppointmentjLabel = new javax.swing.JLabel();
        appointmentIDjLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        appointmentIDjTextField = new javax.swing.JTextField();
        searchjButton = new javax.swing.JButton();
        allCasesjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        markCompletejButton = new javax.swing.JButton();
        appointmentTablejScrollPane = new javax.swing.JScrollPane();
        appointmentTablejTable = new javax.swing.JTable();
        appointmentStatusjTextField = new javax.swing.JTextField();
        appointmentDatejTextField = new javax.swing.JTextField();
        appointmentEndjTextField = new javax.swing.JTextField();
        appointmentStartjTextField = new javax.swing.JTextField();
        appointmentAdminNamejTextField = new javax.swing.JTextField();
        backjButton = new javax.swing.JButton();
        appointmentsjPanel = new javax.swing.JPanel();
        clientDetailsjPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientNotesjTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        appointmentClientNamejTextField = new javax.swing.JTextField();
        clientGenderjTextField = new javax.swing.JTextField();
        clientDOBjTextField = new javax.swing.JTextField();
        clientEmailjTextField = new javax.swing.JTextField();
        clientTeljTextField = new javax.swing.JTextField();
        clientMobjTextField = new javax.swing.JTextField();
        updateNotesjButton = new javax.swing.JButton();
        detailsjPanel = new javax.swing.JPanel();
        clientDetailsjPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        enquiryNotesjTextArea = new javax.swing.JTextArea();
        enquiryNotesjLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        clientDetailsjPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        appointmentNotesjTextArea = new javax.swing.JTextArea();
        appointmentNotesjLabel = new javax.swing.JLabel();
        addToWaitingListjButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowjPanel.setBackground(new java.awt.Color(47, 54, 64));

        headerjPanel.setBackground(new java.awt.Color(47, 54, 64));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Manage Appointments");

        javax.swing.GroupLayout headerjPanelLayout = new javax.swing.GroupLayout(headerjPanel);
        headerjPanel.setLayout(headerjPanelLayout);
        headerjPanelLayout.setHorizontalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerjPanelLayout.setVerticalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        casesjPanel.setBackground(new java.awt.Color(47, 54, 64));

        filterjPanel.setBackground(new java.awt.Color(113, 128, 147));

        searchAppointmentjLabel.setText(" Search Appointments");

        appointmentIDjLabel.setText("Appointment ID");

        jLabel5.setText("Status");

        appointmentIDjTextField.setBackground(new java.awt.Color(220, 221, 225));
        appointmentIDjTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                appointmentIDjTextFieldPropertyChange(evt);
            }
        });

        searchjButton.setText("Search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        allCasesjButton.setText("Next Appointment");
        allCasesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCasesjButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Date");

        jLabel6.setText("From");

        jLabel7.setText("To");

        jLabel8.setText("Assigned By");

        markCompletejButton.setText("Mark Complete");
        markCompletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markCompletejButtonActionPerformed(evt);
            }
        });

        appointmentTablejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appointment ID", "Start Date", "End Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentTablejScrollPane.setViewportView(appointmentTablejTable);

        appointmentStatusjTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentDatejTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentEndjTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentStartjTextField.setBackground(new java.awt.Color(220, 221, 225));

        appointmentAdminNamejTextField.setBackground(new java.awt.Color(220, 221, 225));

        javax.swing.GroupLayout filterjPanelLayout = new javax.swing.GroupLayout(filterjPanel);
        filterjPanel.setLayout(filterjPanelLayout);
        filterjPanelLayout.setHorizontalGroup(
            filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, filterjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appointmentStartjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appointmentEndjTextField)
                        .addGap(6, 6, 6))
                    .addGroup(filterjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(appointmentAdminNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(appointmentTablejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(filterjPanelLayout.createSequentialGroup()
                        .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appointmentIDjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(filterjPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchAppointmentjLabel)
                            .addComponent(appointmentIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointmentDatejTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointmentStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(filterjPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchjButton)
                        .addGap(18, 18, 18)
                        .addComponent(allCasesjButton)))
                .addGap(97, 97, 97))
            .addGroup(filterjPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(markCompletejButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filterjPanelLayout.setVerticalGroup(
            filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchAppointmentjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentIDjLabel)
                    .addComponent(appointmentIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchjButton)
                    .addComponent(allCasesjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentDatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(appointmentStartjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(appointmentEndjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentAdminNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(appointmentTablejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(markCompletejButton)
                .addContainerGap())
        );

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout casesjPanelLayout = new javax.swing.GroupLayout(casesjPanel);
        casesjPanel.setLayout(casesjPanelLayout);
        casesjPanelLayout.setHorizontalGroup(
            casesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casesjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(casesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backjButton)
                    .addComponent(filterjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        casesjPanelLayout.setVerticalGroup(
            casesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casesjPanelLayout.createSequentialGroup()
                .addComponent(filterjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backjButton))
        );

        appointmentsjPanel.setBackground(new java.awt.Color(113, 128, 147));

        clientDetailsjPanel.setBackground(new java.awt.Color(113, 128, 147));

        clientNotesjTextArea.setColumns(20);
        clientNotesjTextArea.setRows(5);
        jScrollPane1.setViewportView(clientNotesjTextArea);

        jLabel2.setText("Client Notes");

        javax.swing.GroupLayout clientDetailsjPanelLayout = new javax.swing.GroupLayout(clientDetailsjPanel);
        clientDetailsjPanel.setLayout(clientDetailsjPanelLayout);
        clientDetailsjPanelLayout.setHorizontalGroup(
            clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientDetailsjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        clientDetailsjPanelLayout.setVerticalGroup(
            clientDetailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientDetailsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Client Details");

        jLabel11.setText("Name");

        jLabel12.setText("Gender");

        jLabel14.setText("DOB");

        jLabel15.setText("Email");

        jLabel16.setText("Tel");

        jLabel17.setText("Mob");

        appointmentClientNamejTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientGenderjTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientDOBjTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientEmailjTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientTeljTextField.setBackground(new java.awt.Color(220, 221, 225));

        clientMobjTextField.setBackground(new java.awt.Color(220, 221, 225));

        updateNotesjButton.setText("Update Notes");

        javax.swing.GroupLayout appointmentsjPanelLayout = new javax.swing.GroupLayout(appointmentsjPanel);
        appointmentsjPanel.setLayout(appointmentsjPanelLayout);
        appointmentsjPanelLayout.setHorizontalGroup(
            appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsjPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clientGenderjTextField)
                    .addComponent(clientDOBjTextField)
                    .addComponent(clientEmailjTextField)
                    .addComponent(clientTeljTextField)
                    .addComponent(clientMobjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(appointmentClientNamejTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointmentsjPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointmentsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientDetailsjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointmentsjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateNotesjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        appointmentsjPanelLayout.setVerticalGroup(
            appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointmentsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addGroup(appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(appointmentClientNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(clientGenderjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDOBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientTeljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(appointmentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(clientMobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clientDetailsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(updateNotesjButton)
                .addGap(37, 37, 37))
        );

        detailsjPanel.setBackground(new java.awt.Color(113, 128, 147));

        clientDetailsjPanel1.setBackground(new java.awt.Color(113, 128, 147));

        enquiryNotesjTextArea.setColumns(20);
        enquiryNotesjTextArea.setRows(5);
        jScrollPane2.setViewportView(enquiryNotesjTextArea);

        enquiryNotesjLabel.setText("Enquiry Notes");

        javax.swing.GroupLayout clientDetailsjPanel1Layout = new javax.swing.GroupLayout(clientDetailsjPanel1);
        clientDetailsjPanel1.setLayout(clientDetailsjPanel1Layout);
        clientDetailsjPanel1Layout.setHorizontalGroup(
            clientDetailsjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsjPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientDetailsjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(clientDetailsjPanel1Layout.createSequentialGroup()
                        .addComponent(enquiryNotesjLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        clientDetailsjPanel1Layout.setVerticalGroup(
            clientDetailsjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientDetailsjPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enquiryNotesjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setText("Enquiry Details");

        clientDetailsjPanel2.setBackground(new java.awt.Color(113, 128, 147));

        appointmentNotesjTextArea.setColumns(20);
        appointmentNotesjTextArea.setRows(5);
        jScrollPane3.setViewportView(appointmentNotesjTextArea);

        appointmentNotesjLabel.setText("Appointment Notes");

        javax.swing.GroupLayout clientDetailsjPanel2Layout = new javax.swing.GroupLayout(clientDetailsjPanel2);
        clientDetailsjPanel2.setLayout(clientDetailsjPanel2Layout);
        clientDetailsjPanel2Layout.setHorizontalGroup(
            clientDetailsjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsjPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientDetailsjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(clientDetailsjPanel2Layout.createSequentialGroup()
                        .addComponent(appointmentNotesjLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        clientDetailsjPanel2Layout.setVerticalGroup(
            clientDetailsjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientDetailsjPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appointmentNotesjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        addToWaitingListjButton.setText("Add to Wating list");

        jLabel9.setText("If client requires addition appointment, add to waiting list.");

        javax.swing.GroupLayout detailsjPanelLayout = new javax.swing.GroupLayout(detailsjPanel);
        detailsjPanel.setLayout(detailsjPanelLayout);
        detailsjPanelLayout.setHorizontalGroup(
            detailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsjPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addToWaitingListjButton)
                .addGap(130, 130, 130))
            .addGroup(detailsjPanelLayout.createSequentialGroup()
                .addGroup(detailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsjPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel13))
                    .addGroup(detailsjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(detailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientDetailsjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientDetailsjPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(detailsjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailsjPanelLayout.setVerticalGroup(
            detailsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientDetailsjPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientDetailsjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addToWaitingListjButton)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout windowjPanelLayout = new javax.swing.GroupLayout(windowjPanel);
        windowjPanel.setLayout(windowjPanelLayout);
        windowjPanelLayout.setHorizontalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowjPanelLayout.createSequentialGroup()
                .addComponent(headerjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(windowjPanelLayout.createSequentialGroup()
                .addComponent(casesjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointmentsjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        windowjPanelLayout.setVerticalGroup(
            windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowjPanelLayout.createSequentialGroup()
                .addComponent(headerjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casesjPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(windowjPanelLayout.createSequentialGroup()
                        .addGroup(windowjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(detailsjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(appointmentsjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(35, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        new CaseworkerDashboard(userLoggedIn).setVisible(true);
        this.dispose();         
        
    }//GEN-LAST:event_backjButtonActionPerformed

    private void appointmentIDjTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_appointmentIDjTextFieldPropertyChange
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_appointmentIDjTextFieldPropertyChange

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        String caseIDEntered = appointmentIDjTextField.getText();
        caseInstance.setCaseTable(caseTablejTable, caseIDEntered);
        
        // caseIDEntereded will be replaced with the ID value of the selected row within the case table, allowing for the query of data by correct case id (which is a forign key).
        //appointmentConnectionInstance.setAppointmentTable(appointmentTablejTable, caseIDEntered);

// TODO add your handling code here:
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void allCasesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCasesjButtonActionPerformed
        // TODO add your handling code here:
        
        caseInstance.setCaseTable(caseTablejTable, "ALL CASES");
    }//GEN-LAST:event_allCasesjButtonActionPerformed

    private void markCompletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markCompletejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markCompletejButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToWaitingListjButton;
    private javax.swing.JButton allCasesjButton;
    private javax.swing.JTextField appointmentAdminNamejTextField;
    private javax.swing.JTextField appointmentClientNamejTextField;
    private javax.swing.JTextField appointmentDatejTextField;
    private javax.swing.JTextField appointmentEndjTextField;
    private javax.swing.JLabel appointmentIDjLabel;
    private javax.swing.JTextField appointmentIDjTextField;
    private javax.swing.JLabel appointmentNotesjLabel;
    private javax.swing.JTextArea appointmentNotesjTextArea;
    private javax.swing.JTextField appointmentStartjTextField;
    private javax.swing.JTextField appointmentStatusjTextField;
    private javax.swing.JScrollPane appointmentTablejScrollPane;
    private javax.swing.JTable appointmentTablejTable;
    private javax.swing.JPanel appointmentsjPanel;
    private javax.swing.JButton backjButton;
    private javax.swing.JPanel casesjPanel;
    private javax.swing.JTextField clientDOBjTextField;
    private javax.swing.JPanel clientDetailsjPanel;
    private javax.swing.JPanel clientDetailsjPanel1;
    private javax.swing.JPanel clientDetailsjPanel2;
    private javax.swing.JTextField clientEmailjTextField;
    private javax.swing.JTextField clientGenderjTextField;
    private javax.swing.JTextField clientMobjTextField;
    private javax.swing.JTextArea clientNotesjTextArea;
    private javax.swing.JTextField clientTeljTextField;
    private javax.swing.JPanel detailsjPanel;
    private javax.swing.JLabel enquiryNotesjLabel;
    private javax.swing.JTextArea enquiryNotesjTextArea;
    private javax.swing.JPanel filterjPanel;
    private javax.swing.JPanel headerjPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton markCompletejButton;
    private javax.swing.JLabel searchAppointmentjLabel;
    private javax.swing.JButton searchjButton;
    private javax.swing.JButton updateNotesjButton;
    private javax.swing.JPanel windowjPanel;
    // End of variables declaration//GEN-END:variables
}
