/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package residentsupportsystem;

import java.text.ParseException;
import java.time.LocalDate;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.DateTimeException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author robbieoneill
 */
public class CaseworkerManageWorkingTime extends javax.swing.JFrame {
    int userLoggedIn;
    WorkHours workHours = new WorkHours();
    Appointment appointment = new Appointment();
    /** Creates new form caseworkerManageDetails */
    public CaseworkerManageWorkingTime(int userID) {
        userLoggedIn = userID;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        mondayjCheckBox = new javax.swing.JCheckBox();
        tuesdayjCheckBox = new javax.swing.JCheckBox();
        thursdayjCheckBox = new javax.swing.JCheckBox();
        wednesdayjCheckBox = new javax.swing.JCheckBox();
        saturdayjCheckBox = new javax.swing.JCheckBox();
        sundayjCheckBox = new javax.swing.JCheckBox();
        fridayjCheckBox = new javax.swing.JCheckBox();
        mondayFromjLabel = new javax.swing.JLabel();
        tuesdayFromjLabel = new javax.swing.JLabel();
        wednesdayFromjLabel = new javax.swing.JLabel();
        thursdayFromjLabel = new javax.swing.JLabel();
        fridayFromjLabel = new javax.swing.JLabel();
        saturdayFromjLabel = new javax.swing.JLabel();
        sundayFromjLabel = new javax.swing.JLabel();
        mondayStartjComboBox = new javax.swing.JComboBox<>();
        mondayTojLabel = new javax.swing.JLabel();
        mondayEndjComboBox = new javax.swing.JComboBox<>();
        tuesdayStartjComboBox = new javax.swing.JComboBox<>();
        tuesdayTojLabel = new javax.swing.JLabel();
        tuesdayEndjComboBox = new javax.swing.JComboBox<>();
        wednesdayStartjComboBox = new javax.swing.JComboBox<>();
        wednesdayTojLabel = new javax.swing.JLabel();
        wednesdayEndjComboBox = new javax.swing.JComboBox<>();
        thursdayStartjComboBox = new javax.swing.JComboBox<>();
        thursdayTojLabel = new javax.swing.JLabel();
        thursdayEndjComboBox = new javax.swing.JComboBox<>();
        fridayStartjComboBox = new javax.swing.JComboBox<>();
        fridayTojLabel = new javax.swing.JLabel();
        fridayEndjComboBox = new javax.swing.JComboBox<>();
        saturdayStartjComboBox = new javax.swing.JComboBox<>();
        saturdayTojLabel = new javax.swing.JLabel();
        saturdayEndjComboBox = new javax.swing.JComboBox<>();
        sundayStartjComboBox = new javax.swing.JComboBox<>();
        sundayTojLabel = new javax.swing.JLabel();
        sundayEndjComboBox = new javax.swing.JComboBox<>();
        setHourHeadingjLabel = new javax.swing.JLabel();
        savejButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workHistoryjTable = new javax.swing.JTable();
        searchjButton = new javax.swing.JButton();
        weekSearchjTextField = new javax.swing.JTextField();
        weekSearchjLabel = new javax.swing.JLabel();
        viewAlljButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 54, 64));

        jPanel2.setBackground(new java.awt.Color(47, 54, 64));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 238, 238));
        jLabel18.setText("Manage Working Hours ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(113, 128, 147));

        jPanel4.setBackground(new java.awt.Color(220, 221, 225));
        jPanel4.setForeground(new java.awt.Color(220, 221, 225));

        mondayjCheckBox.setText("Monday");
        mondayjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayjCheckBoxActionPerformed(evt);
            }
        });

        tuesdayjCheckBox.setText("Tuesday");
        tuesdayjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayjCheckBoxActionPerformed(evt);
            }
        });

        thursdayjCheckBox.setText("Thursday");
        thursdayjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayjCheckBoxActionPerformed(evt);
            }
        });

        wednesdayjCheckBox.setText("Wednesday");
        wednesdayjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayjCheckBoxActionPerformed(evt);
            }
        });

        saturdayjCheckBox.setText("Saturday");
        saturdayjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayjCheckBoxActionPerformed(evt);
            }
        });

        sundayjCheckBox.setText("Sunday");
        sundayjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayjCheckBoxActionPerformed(evt);
            }
        });

        fridayjCheckBox.setText("Friday");
        fridayjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayjCheckBoxActionPerformed(evt);
            }
        });

        mondayFromjLabel.setText("From");

        tuesdayFromjLabel.setText("From");

        wednesdayFromjLabel.setText("From");

        thursdayFromjLabel.setText("From");

        fridayFromjLabel.setText("From");

        saturdayFromjLabel.setText("From");

        sundayFromjLabel.setText("From");

        mondayStartjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Start", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        mondayTojLabel.setText("To");

        mondayEndjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "End", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        tuesdayStartjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Start", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        tuesdayTojLabel.setText("To");

        tuesdayEndjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "End", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        wednesdayStartjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Start", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        wednesdayTojLabel.setText("To");

        wednesdayEndjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "End", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        thursdayStartjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Start", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        thursdayTojLabel.setText("To");

        thursdayEndjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "End", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        fridayStartjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Start", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        fridayTojLabel.setText("To");

        fridayEndjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "End", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        saturdayStartjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Start", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        saturdayTojLabel.setText("To");

        saturdayEndjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "End", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        sundayStartjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Start", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        sundayTojLabel.setText("To");

        sundayEndjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "End", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tuesdayjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mondayjCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wednesdayjCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thursdayjCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fridayjCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saturdayjCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sundayjCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(mondayFromjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(mondayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mondayTojLabel)
                        .addGap(18, 18, 18)
                        .addComponent(mondayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tuesdayFromjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(tuesdayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tuesdayTojLabel)
                        .addGap(18, 18, 18)
                        .addComponent(tuesdayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(wednesdayFromjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(wednesdayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(wednesdayTojLabel)
                        .addGap(18, 18, 18)
                        .addComponent(wednesdayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(thursdayFromjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(thursdayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(thursdayTojLabel)
                        .addGap(18, 18, 18)
                        .addComponent(thursdayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(fridayFromjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fridayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fridayTojLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fridayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(saturdayFromjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(saturdayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saturdayTojLabel)
                        .addGap(18, 18, 18)
                        .addComponent(saturdayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(sundayFromjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sundayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sundayTojLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sundayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mondayjCheckBox)
                    .addComponent(mondayFromjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mondayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mondayTojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mondayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tuesdayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tuesdayTojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tuesdayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tuesdayjCheckBox)
                        .addComponent(tuesdayFromjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wednesdayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wednesdayTojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wednesdayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wednesdayjCheckBox)
                        .addComponent(wednesdayFromjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(thursdayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thursdayTojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thursdayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(thursdayjCheckBox)
                        .addComponent(thursdayFromjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fridayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fridayTojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fridayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fridayjCheckBox)
                        .addComponent(fridayFromjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saturdayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saturdayTojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saturdayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saturdayjCheckBox)
                        .addComponent(saturdayFromjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sundayStartjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sundayTojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sundayEndjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sundayjCheckBox)
                        .addComponent(sundayFromjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setHourHeadingjLabel.setText("Set Workinng Hours for Week Comencing:");

        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(savejButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(setHourHeadingjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(setHourHeadingjLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savejButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(113, 128, 147));

        jLabel2.setText("View your past work hours");

        workHistoryjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Week", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ));
        jScrollPane1.setViewportView(workHistoryjTable);

        searchjButton.setText("Search");

        weekSearchjTextField.setBackground(new java.awt.Color(220, 221, 225));

        weekSearchjLabel.setText("Week Start Date: ");

        viewAlljButton.setText("View All");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(weekSearchjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(weekSearchjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchjButton)
                        .addGap(18, 18, 18)
                        .addComponent(viewAlljButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchjButton)
                    .addComponent(weekSearchjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weekSearchjLabel)
                    .addComponent(viewAlljButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backjButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(backjButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mondayjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondayjCheckBoxActionPerformed

    private void tuesdayjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesdayjCheckBoxActionPerformed

    private void thursdayjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursdayjCheckBoxActionPerformed

    private void wednesdayjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayjCheckBoxActionPerformed

    private void saturdayjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturdayjCheckBoxActionPerformed

    private void sundayjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sundayjCheckBoxActionPerformed

    private void fridayjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fridayjCheckBoxActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed

        LocalDate startOfWeekDate = workHours.startOfNextConsecutiveWeek();
        String startTimeEntered = "";
        String endTimeEntered = "";
        
        if (mondayjCheckBox.isSelected()){
            startTimeEntered = (mondayStartjComboBox.getSelectedItem().toString());
            endTimeEntered = (mondayEndjComboBox.getSelectedItem().toString());
            
            try {
                Date validStartTime = new SimpleDateFormat("HH:mm").parse(startTimeEntered);
                Date validEndTime = new SimpleDateFormat("HH:mm").parse(endTimeEntered);
                int startTime = validStartTime.getHours();
                System.out.println("START TIME ENTERED BY USER: "+startTime);
                int endTime = validEndTime.getHours();
                int numberOfHours = (5);
                int dayIndex = 0;
                int userID = 1;
                appointment.addAppointment(startOfWeekDate, dayIndex, userID, numberOfHours, startTime, endTime);
            } catch (ParseException ex) {
                Logger.getLogger(CaseworkerManageWorkingTime.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(tuesdayjCheckBox.isSelected()){
            JOptionPane.showMessageDialog(rootPane,"Checkbox Tuesday is Checked","Info", 2);
        }
        if(wednesdayjCheckBox.isSelected()){
            JOptionPane.showMessageDialog(rootPane,"Checkbox Tuesday is Checked","Info", 2);
        }
        if(thursdayjCheckBox.isSelected()){
            JOptionPane.showMessageDialog(rootPane,"Checkbox Tuesday is Checked","Info", 2);
        }
        if(fridayjCheckBox.isSelected()){
            JOptionPane.showMessageDialog(rootPane,"Checkbox Tuesday is Checked","Info", 2);
        }
        if(saturdayjCheckBox.isSelected()){
            JOptionPane.showMessageDialog(rootPane,"Checkbox Tuesday is Checked","Info", 2);
        }
        if(sundayjCheckBox.isSelected()){
            JOptionPane.showMessageDialog(rootPane,"Checkbox Tuesday is Checked","Info", 2);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_savejButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
    new CaseworkerDashboard(userLoggedIn).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox<String> fridayEndjComboBox;
    private javax.swing.JLabel fridayFromjLabel;
    private javax.swing.JComboBox<String> fridayStartjComboBox;
    private javax.swing.JLabel fridayTojLabel;
    private javax.swing.JCheckBox fridayjCheckBox;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mondayEndjComboBox;
    private javax.swing.JLabel mondayFromjLabel;
    private javax.swing.JComboBox<String> mondayStartjComboBox;
    private javax.swing.JLabel mondayTojLabel;
    private javax.swing.JCheckBox mondayjCheckBox;
    private javax.swing.JComboBox<String> saturdayEndjComboBox;
    private javax.swing.JLabel saturdayFromjLabel;
    private javax.swing.JComboBox<String> saturdayStartjComboBox;
    private javax.swing.JLabel saturdayTojLabel;
    private javax.swing.JCheckBox saturdayjCheckBox;
    private javax.swing.JButton savejButton;
    private javax.swing.JButton searchjButton;
    private javax.swing.JLabel setHourHeadingjLabel;
    private javax.swing.JComboBox<String> sundayEndjComboBox;
    private javax.swing.JLabel sundayFromjLabel;
    private javax.swing.JComboBox<String> sundayStartjComboBox;
    private javax.swing.JLabel sundayTojLabel;
    private javax.swing.JCheckBox sundayjCheckBox;
    private javax.swing.JComboBox<String> thursdayEndjComboBox;
    private javax.swing.JLabel thursdayFromjLabel;
    private javax.swing.JComboBox<String> thursdayStartjComboBox;
    private javax.swing.JLabel thursdayTojLabel;
    private javax.swing.JCheckBox thursdayjCheckBox;
    private javax.swing.JComboBox<String> tuesdayEndjComboBox;
    private javax.swing.JLabel tuesdayFromjLabel;
    private javax.swing.JComboBox<String> tuesdayStartjComboBox;
    private javax.swing.JLabel tuesdayTojLabel;
    private javax.swing.JCheckBox tuesdayjCheckBox;
    private javax.swing.JButton viewAlljButton;
    private javax.swing.JComboBox<String> wednesdayEndjComboBox;
    private javax.swing.JLabel wednesdayFromjLabel;
    private javax.swing.JComboBox<String> wednesdayStartjComboBox;
    private javax.swing.JLabel wednesdayTojLabel;
    private javax.swing.JCheckBox wednesdayjCheckBox;
    private javax.swing.JLabel weekSearchjLabel;
    private javax.swing.JTextField weekSearchjTextField;
    private javax.swing.JTable workHistoryjTable;
    // End of variables declaration//GEN-END:variables

}
